2008-05-27  Diego Novillo  <dnovillo@google.com>
	* tree-gimple.c (get_gimple_rhs_class): Handle
	POLYNOMIAL_CHREC.
	* tree-cfg.c (verify_types_in_gimple_assign): Do not
	check every operand against the LHS type for tcc_binary
	expressions.

2008-05-26  Diego Novillo  <dnovillo@google.com>

	Merge with mainline @135951.

	* configure.ac (ACX_PKGVERSION): Update revision merge string.
	* configure: Regenerate.




git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/gimple-tuples-branch@136036 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/libstdc++-v3/configure b/libstdc++-v3/configure
--- a/libstdc++-v3/configure
+++ b/libstdc++-v3/configure
@@ -4146,10 +4146,12 @@ echo "$as_me: OS config directory is $os_include_dir" >&6;}
 
 
 
-enable_dlopen=yes
+if test "x${with_newlib}" != "xyes"; then
+  enable_dlopen=yes
 
 
 
+fi
 
 
 macro_version='2.1a'
@@ -4666,13 +4668,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4669: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4671: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4672: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4674: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4675: output\"" >&5)
+  (eval echo "\"\$as_me:4677: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5716,7 +5718,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5719 "configure"' > conftest.$ac_ext
+  echo '#line 5721 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7178,11 +7180,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7181: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7183: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7185: \$? = $ac_status" >&5
+   echo "$as_me:7187: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7500,11 +7502,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7503: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7505: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7507: \$? = $ac_status" >&5
+   echo "$as_me:7509: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7605,11 +7607,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7608: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7610: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7612: \$? = $ac_status" >&5
+   echo "$as_me:7614: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7660,11 +7662,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7663: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7665: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7667: \$? = $ac_status" >&5
+   echo "$as_me:7669: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10512,7 +10514,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10515 "configure"
+#line 10517 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10612,7 +10614,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10615 "configure"
+#line 10617 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12650,11 +12652,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12653: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12655: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12657: \$? = $ac_status" >&5
+   echo "$as_me:12659: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12749,11 +12751,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12752: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12754: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12756: \$? = $ac_status" >&5
+   echo "$as_me:12758: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12801,11 +12803,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12804: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12806: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12808: \$? = $ac_status" >&5
+   echo "$as_me:12810: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13850,7 +13852,7 @@ fi;
     #
     # Fake what AC_TRY_COMPILE does.  XXX Look at redoing this new-style.
     cat > conftest.$ac_ext << EOF
-#line 13853 "configure"
+#line 13855 "configure"
 struct S { ~S(); };
 void bar();
 void foo()
@@ -13996,7 +13998,7 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
   # unnecessary for a builtins test.
 
     cat > conftest.$ac_ext << EOF
-#line 13999 "configure"
+#line 14001 "configure"
 int main()
 {
   // NB: _Atomic_word not necessarily int.
@@ -14036,7 +14038,7 @@ echo "${ECHO_T}$enable_atomic_builtinsi" >&6
     rm -f conftest*
 
     cat > conftest.$ac_ext << EOF
-#line 14039 "configure"
+#line 14041 "configure"
 int main()
 {
   typedef bool atomic_type;
@@ -16396,6 +16398,7 @@ f = cabsf(tmpf);
 	tmpf = ctanf(tmpf);
 	tmpf = ctanhf(tmpf);
 	tmpf = cpowf(tmpf, tmpf);
+	tmpf = cprojf(tmpf);
 	d = cabs(tmpd);
 	d = carg(tmpd);
 	tmpd = ccos(tmpd);
@@ -16408,6 +16411,7 @@ f = cabsf(tmpf);
 	tmpd = ctan(tmpd);
 	tmpd = ctanh(tmpd);
 	tmpd = cpow(tmpd, tmpd);
+	tmpd = cproj(tmpd);
 	ld = cabsl(tmpld);
 	ld = cargl(tmpld);
 	tmpld = ccosl(tmpld);
@@ -16420,6 +16424,7 @@ f = cabsf(tmpf);
 	tmpld = ctanl(tmpld);
 	tmpld = ctanhl(tmpld);
 	tmpld = cpowl(tmpld, tmpld);
+	tmpld = cprojl(tmpld);
 
   ;
   return 0;
@@ -16492,6 +16497,7 @@ f = cabsf(tmpf);
 	tmpf = ctanf(tmpf);
 	tmpf = ctanhf(tmpf);
 	tmpf = cpowf(tmpf, tmpf);
+	tmpf = cprojf(tmpf);
 	d = cabs(tmpd);
 	d = carg(tmpd);
 	tmpd = ccos(tmpd);
@@ -16504,6 +16510,7 @@ f = cabsf(tmpf);
 	tmpd = ctan(tmpd);
 	tmpd = ctanh(tmpd);
 	tmpd = cpow(tmpd, tmpd);
+	tmpd = cproj(tmpd);
 	ld = cabsl(tmpld);
 	ld = cargl(tmpld);
 	tmpld = ccosl(tmpld);
@@ -16516,6 +16523,7 @@ f = cabsf(tmpf);
 	tmpld = ctanl(tmpld);
 	tmpld = ctanhl(tmpld);
 	tmpld = cpowl(tmpld, tmpld);
+	tmpld = cprojl(tmpld);
 
   ;
   return 0;
@@ -17840,8 +17848,8 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
-echo "$as_me:$LINENO: checking for sys_nerr" >&5
-echo $ECHO_N "checking for sys_nerr... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for EBADMSG" >&5
+echo $ECHO_N "checking for EBADMSG... $ECHO_C" >&6
 if test "${glibcxx_cv_system_error9+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -17856,7 +17864,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-int i = sys_nerr;
+int i = EBADMSG;
   ;
   return 0;
 }
@@ -17899,12 +17907,12 @@ echo "${ECHO_T}$glibcxx_cv_system_error9" >&6
 if test x"$glibcxx_cv_system_error9" = x"yes"; then
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_SYS_NERR 1
+#define HAVE_EBADMSG 1
 _ACEOF
 
 fi
-echo "$as_me:$LINENO: checking for EBADMSG" >&5
-echo $ECHO_N "checking for EBADMSG... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for ECANCELED" >&5
+echo $ECHO_N "checking for ECANCELED... $ECHO_C" >&6
 if test "${glibcxx_cv_system_error10+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -17919,7 +17927,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-int i = EBADMSG;
+int i = ECANCELED;
   ;
   return 0;
 }
@@ -17962,12 +17970,12 @@ echo "${ECHO_T}$glibcxx_cv_system_error10" >&6
 if test x"$glibcxx_cv_system_error10" = x"yes"; then
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_EBADMSG 1
+#define HAVE_ECANCELED 1
 _ACEOF
 
 fi
-echo "$as_me:$LINENO: checking for ECANCELED" >&5
-echo $ECHO_N "checking for ECANCELED... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for EOVERFLOW" >&5
+echo $ECHO_N "checking for EOVERFLOW... $ECHO_C" >&6
 if test "${glibcxx_cv_system_error11+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -17982,7 +17990,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-int i = ECANCELED;
+int i = EOVERFLOW;
   ;
   return 0;
 }
@@ -18025,12 +18033,12 @@ echo "${ECHO_T}$glibcxx_cv_system_error11" >&6
 if test x"$glibcxx_cv_system_error11" = x"yes"; then
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_ECANCELED 1
+#define HAVE_EOVERFLOW 1
 _ACEOF
 
 fi
-echo "$as_me:$LINENO: checking for EOVERFLOW" >&5
-echo $ECHO_N "checking for EOVERFLOW... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for ENOTSUP" >&5
+echo $ECHO_N "checking for ENOTSUP... $ECHO_C" >&6
 if test "${glibcxx_cv_system_error12+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -18045,7 +18053,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-int i = EOVERFLOW;
+int i = ENOTSUP;
   ;
   return 0;
 }
@@ -18088,12 +18096,12 @@ echo "${ECHO_T}$glibcxx_cv_system_error12" >&6
 if test x"$glibcxx_cv_system_error12" = x"yes"; then
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_EOVERFLOW 1
+#define HAVE_ENOTSUP 1
 _ACEOF
 
 fi
-echo "$as_me:$LINENO: checking for ENOTSUP" >&5
-echo $ECHO_N "checking for ENOTSUP... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for EIDRM" >&5
+echo $ECHO_N "checking for EIDRM... $ECHO_C" >&6
 if test "${glibcxx_cv_system_error13+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -18108,7 +18116,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-int i = ENOTSUP;
+int i = EIDRM;
   ;
   return 0;
 }
@@ -18151,76 +18159,13 @@ echo "${ECHO_T}$glibcxx_cv_system_error13" >&6
 if test x"$glibcxx_cv_system_error13" = x"yes"; then
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_ENOTSUP 1
-_ACEOF
-
-fi
-echo "$as_me:$LINENO: checking for EIDRM" >&5
-echo $ECHO_N "checking for EIDRM... $ECHO_C" >&6
-if test "${glibcxx_cv_system_error14+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <errno.h>
-int
-main ()
-{
-int i = EIDRM;
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  glibcxx_cv_system_error14=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-glibcxx_cv_system_error14=no
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-
-fi
-
-echo "$as_me:$LINENO: result: $glibcxx_cv_system_error14" >&5
-echo "${ECHO_T}$glibcxx_cv_system_error14" >&6
-if test x"$glibcxx_cv_system_error14" = x"yes"; then
-
-cat >>confdefs.h <<\_ACEOF
 #define HAVE_EIDRM 1
 _ACEOF
 
 fi
 echo "$as_me:$LINENO: checking for ETXTBSY" >&5
 echo $ECHO_N "checking for ETXTBSY... $ECHO_C" >&6
-if test "${glibcxx_cv_system_error15+set}" = set; then
+if test "${glibcxx_cv_system_error14+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
@@ -18261,20 +18206,20 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  glibcxx_cv_system_error15=yes
+  glibcxx_cv_system_error14=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-glibcxx_cv_system_error15=no
+glibcxx_cv_system_error14=no
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 
 fi
 
-echo "$as_me:$LINENO: result: $glibcxx_cv_system_error15" >&5
-echo "${ECHO_T}$glibcxx_cv_system_error15" >&6
-if test x"$glibcxx_cv_system_error15" = x"yes"; then
+echo "$as_me:$LINENO: result: $glibcxx_cv_system_error14" >&5
+echo "${ECHO_T}$glibcxx_cv_system_error14" >&6
+if test x"$glibcxx_cv_system_error14" = x"yes"; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_ETXTBSY 1
