Merge from HEAD at ra-merge-20031009.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/new-regalloc-branch@72296 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/maintainer-scripts/gcc_release b/maintainer-scripts/gcc_release
--- a/maintainer-scripts/gcc_release
+++ b/maintainer-scripts/gcc_release
@@ -11,20 +11,20 @@
 #
 # Copyright (c) 2001, 2002 Free Software Foundation.
 #
-# This file is part of GNU CC.
+# This file is part of GCC.
 #
-# GNU CC is free software; you can redistribute it and/or modify
+# GCC is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2, or (at your option)
 # any later version.
 #
-# GNU CC is distributed in the hope that it will be useful,
+# GCC is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with GNU CC; see the file COPYING.  If not, write to
+# along with GCC; see the file COPYING.  If not, write to
 # the Free Software Foundation, 59 Temple Place - Suite 330,
 # Boston, MA 02111-1307, USA.
 #
@@ -64,12 +64,21 @@ inform() {
 
 usage() {
 cat <<EOF
-gcc_release     [-d destination]
-                [-u username]
-		[-r release]
-		[-t tag]
-		[-p previous-tarball]
-		[-s] [-f] [-l]
+gcc_release -r release [-f] [further options]
+gcc_release -s name:cvsbranch [further options]
+
+Options:
+
+  -r release           Version of the form X.Y or X.Y.Z.
+  -s name:cvsbranch    Create a snapshot, not a real release.
+
+  -d destination       Local working directory where we will build the release
+                       (default=${HOME}).
+  -f                   Create a final release (and update ChangeLogs,...).
+  -l                   Indicate that we are running on gcc.gnu.org.
+  -p previous-tarball  Location of a previous tarball (to generate diff files).
+  -t tag               Tag to mark the release in CVS.
+  -u username          Username for upload operations.
 EOF
     exit 1
 }
@@ -110,27 +119,32 @@ build_sources() {
     inform "Updating ChangeLogs and version files"
 
     ${CVS} co -d "`basename ${SOURCE_DIRECTORY}`" \
-           -r ${BRANCH} gcc || \
+           -r ${CVSBRANCH} gcc || \
            error "Could not check out release sources"
     for x in `find ${SOURCE_DIRECTORY} -name ChangeLog`; do
-      cat - ${x} > ${x}.new <<EOF
+      # Update this ChangeLog file only if it does not yet contain the
+      # entry we are going to add.  (This is a safety net for repeated
+      # runs of this script for the same release.)
+      if ! grep "GCC ${RELEASE} released." ${x} > /dev/null ; then       
+        cat - ${x} > ${x}.new <<EOF
 ${LONG_DATE}  Release Manager
 
-	* GCC ${RELEASE} Released.
+	* GCC ${RELEASE} released.
 
 EOF
-      mv ${x}.new ${x} || \
-        error "Could not update ${x}"
-      (changedir `dirname ${x}` && \
-        ${CVS} ci -m 'Mark ChangeLog' `basename ${x}`) || \
-        error "Could not commit ${x}"
+        mv ${x}.new ${x} || \
+            error "Could not update ${x}"
+        (changedir `dirname ${x}` && \
+            ${CVS} ci -m 'Mark ChangeLog' `basename ${x}`) || \
+            error "Could not commit ${x}"
+      fi
     done
 
     # Update `gcc/version.c'.
     for x in gcc/version.c; do 
       y=`basename ${x}`
       (changedir `dirname ${SOURCE_DIRECTORY}/${x}` && \
-          sed -e 's|= \".*\"|= \"'${RELEASE}'\"|g' < ${y} > ${y}.new && \
+          sed -e 's|version_string\[\] = \".*\"|version_string\[\] = \"'${RELEASE}'\"|g' < ${y} > ${y}.new && \
 	  mv ${y}.new ${y} && \
           ${CVS} ci -m 'Update version' ${y}) || \
 	  error "Could not update ${x}"
@@ -144,27 +158,46 @@ EOF
 
   # Tag the sources.
   if [ -n "${TAG}" ]; then
-    inform "Tagging release sources"
-    ${CVS} rtag -r ${BRANCH} -F ${TAG} gcc || \
-      error "Could not tag release sources"
-    BRANCH=$TAG
+    inform "Tagging sources as ${TAG}"
+    ${CVS} rtag -r ${CVSBRANCH} -F ${TAG} gcc || \
+      error "Could not tag sources"
+    EXPORTTAG="-r${TAG}"
+    EXPORTDATE=""
+  else
+    if [ ${CVSBRANCH} != "HEAD" ]; then
+      EXPORTTAG="-r${CVSBRANCH}"
+    else
+      # HEAD is the default branch, no need to specify it.
+      EXPORTTAG=""
+    fi
+    EXPORTDATE="-D`date -u +"%Y-%m-%d %H:%M"` UTC"
   fi
 
   # Export the current sources.
-  inform "Retrieving release sources"
-  ${CVS} \
-       export -d "`basename ${SOURCE_DIRECTORY}`" \
-       -r ${BRANCH} gcc || \
-    error "Could not retrieve release sources"
+  inform "Retrieving sources (cvs export ${EXPORTTAG} ${EXPORTDATE} gcc)"
 
-  # Run gcc_update on them to set up the timestamps nicely.
+  if [ -z "${EXPORTTAG}" ]; then
+    ${CVS} export -d "`basename ${SOURCE_DIRECTORY}`" \
+       "${EXPORTDATE}" gcc || \
+      error "Could not retrieve sources"
+  elif [ -z "${EXPORTDATE}" ]; then
+    ${CVS} export -d "`basename ${SOURCE_DIRECTORY}`" \
+       "${EXPORTTAG}" gcc || \
+      error "Could not retrieve sources"
+  else
+    error "Cannot specify -r and -D at the same time"
+  fi
+
+  # Run gcc_update on them to set up the timestamps nicely, and (re)write
+  # the LAST_UPDATED file containing the CVS tag/date used.
   changedir "gcc-${RELEASE}"
   contrib/gcc_update --touch
+  echo "Obtained from CVS: ${EXPORTTAG} ${EXPORTDATE}" > LAST_UPDATED
 
   # Obtain some documentation files from the wwwdocs module.
   inform "Retrieving HTML documentation"
   changedir "${WORKING_DIRECTORY}"
-  for x in bugs gnats faq; do
+  for x in bugs faq; do
     (${CVS} export -r HEAD wwwdocs/htdocs/${x}.html && \
      cp ${WORKING_DIRECTORY}/wwwdocs/htdocs/${x}.html \
         ${SOURCE_DIRECTORY}) || \
@@ -178,7 +211,7 @@ EOF
     (${ENV} TERM=vt100 lynx -dump $file \
        | sed -e "s#file://localhost`/bin/pwd`\(.*\)#http://gcc.gnu.org\1#g" \
        > $newfile) || \
-     error "Could not regenerate documentation"
+     error "Could not generate text-only version of ${file}"
   done
 
   # For a prerelease or real release, we need to generate additional
@@ -231,11 +264,11 @@ EOF
 
 build_tarfile() {
   # Get the name of the destination tar file.
-  TARFILE="$1.tar.gz"
+  TARFILE="$1.tar.bz2"
   shift
 
   # Build the tar file itself.
-  (${TAR} cf - "$@" | ${GZIP} > ${TARFILE}) || \
+  (${TAR} cf - "$@" | ${BZIP2} > ${TARFILE}) || \
     error "Could not build tarfile"
   FILE_LIST="${FILE_LIST} ${TARFILE}"
 }
@@ -274,11 +307,11 @@ build_tarfiles() {
     `basename ${SOURCE_DIRECTORY}`
 }
 
-# Build .bz2 files.
-build_bzip2() {
+# Build .gz files.
+build_gzip() {
   for f in ${FILE_LIST}; do
-    bzfile=${f%.gz}.bz2
-    (zcat $f | ${BZIP2} > ${bzfile}) || error "Could not create ${bzfile}"
+    target=${f%.bz2}.gz
+    (${BZIP2} -d -c $f | ${GZIP} > ${target}) || error "Could not create ${target}"
   done
 }
 
@@ -286,15 +319,19 @@ build_bzip2() {
 build_diffs() {
   old_dir=${1%/*}
   old_file=${1##*/}
-  old_vers=${old_file%.tar.gz}
+  old_vers=${old_file%.tar.bz2}
   old_vers=${old_vers#gcc-}
   inform "Building diffs against version $old_vers"
   for f in gcc gcc-ada gcc-g++ gcc-g77 gcc-java gcc-objc gcc-testsuite gcc-core; do
-    old_tar=${old_dir}/${f}-${old_vers}.tar.gz
-    new_tar=${WORKING_DIRECTORY}/${f}-${RELEASE}.tar.gz
-    if [ -e $old_tar ] && [ -e $new_tar ]; then
+    old_tar=${old_dir}/${f}-${old_vers}.tar.bz2
+    new_tar=${WORKING_DIRECTORY}/${f}-${RELEASE}.tar.bz2
+    if [ ! -e $old_tar ]; then
+      inform "$old_tar not found; not generating diff file"
+    elif [ ! -e $new_tar ]; then
+      inform "$new_tar not found; not generating diff file"
+    else
       build_diff $old_tar gcc-${old_vers} $new_tar gcc-${RELEASE} \
-        ${f}-${old_vers}-${RELEASE}.diff.gz
+        ${f}-${old_vers}-${RELEASE}.diff.bz2
     fi
   done
 }
@@ -305,20 +342,19 @@ build_diff() {
   tmpdir=gccdiff.$$
   mkdir $tmpdir || error "Could not create directory $tmpdir"
   changedir $tmpdir
-  tar xfz $1 || error "Could not unpack $1 for diffs"
-  tar xfz $3 || error "Could not unpack $3 for diffs"
-  ${DIFF} $2 $4 > ../${5%.gz}
+  (${BZIP2} -d -c $1 | ${TAR} xf - ) || error "Could not unpack $1 for diffs"
+  (${BZIP2} -d -c $3 | ${TAR} xf - ) || error "Could not unpack $3 for diffs"
+  ${DIFF} $2 $4 > ../${5%.bz2}
   if [ $? -eq 2 ]; then
     error "Trouble making diffs from $1 to $3"
   fi
-  ${GZIP} ../${5%.gz} || error "Could not gzip ../${5%.gz}"
+  ${BZIP2} ../${5%.bz2} || error "Could not generate ../$5"
   changedir ..
   rm -rf $tmpdir
   FILE_LIST="${FILE_LIST} $5"
 }
 
 # Upload the files to the FTP server.
-
 upload_files() {
   inform "Uploading files"
 
@@ -326,22 +362,64 @@ upload_files() {
 
   # Make sure the directory exists on the server.
   if [ $LOCAL -eq 0 ]; then
-    ${SSH} -l ${GCC_USERNAME} ${GCC_HOSTNAME} mkdir ${FTP_PATH}
+    ${SSH} -l ${GCC_USERNAME} ${GCC_HOSTNAME} \
+      mkdir -p "${FTP_PATH}/diffs"
     UPLOAD_PATH="${GCC_USERNAME}@${GCC_HOSTNAME}:${FTP_PATH}"
   else
-    mkdir -p "${FTP_PATH}" \
+    mkdir -p "${FTP_PATH}/diffs" \
       || error "Could not create \`${FTP_PATH}'"
     UPLOAD_PATH=${FTP_PATH}
   fi
 
+  # Then copy files to their respective (sub)directories.
   for x in gcc*.gz gcc*.bz2; do
     if [ -e ${x} ]; then
       # Make sure the file will be readable on the server.
       chmod a+r ${x}
       # Copy it.
-      ${SCP} ${x} ${UPLOAD_PATH} || error "Could not upload ${x}"
+      case ${x} in
+        *.diff.*)
+          SUBDIR="diffs/";
+          ;;
+        *)
+          SUBDIR="";
+      esac
+      ${SCP} ${x} ${UPLOAD_PATH}/${SUBDIR} \
+        || error "Could not upload ${x}"
     fi
   done
+}
+
+# Announce a snapshot, both on the web and via mail.
+announce_snapshot() {
+  inform "Updating links and READMEs on the FTP server"
+  
+  TEXT_DATE=`date --date=$DATE +%B\ %d,\ %Y`
+  cd ~ftp/pub/gcc/snapshots
+  sed -e "s%@DATE@%$DATE%g" \
+    -e "s%@TEXT_DATE@%$TEXT_DATE%g" \
+    -e "s%@LAST_DATE@%$LAST_DATE%g" \
+    -e "s%@BRANCH@%${BRANCH}%g" \
+    -e "s%@RELEASE@%${RELEASE}%g" \
+    -e "s%@EXPORT@%${EXPORTTAG} ${EXPORTDATE}%g" \
+    ~/scripts/snapshot-README > $$
+  mv $$ ${RELEASE}/README
+  sed -e "s%@DATE@%$DATE%g" \
+    -e "s%@TEXT_DATE@%$TEXT_DATE%g" \
+    -e "s%@LAST_DATE@%$LAST_DATE%g" \
+    -e "s%@BRANCH@%${BRANCH}%g" \
+    -e "s%@RELEASE@%${RELEASE}%g" \
+    -e "s%@EXPORT@%${EXPORTTAG} ${EXPORTDATE}%g" \
+    ~/scripts/snapshot-index.html > $$
+  mv $$ ${RELEASE}/index.html
+
+  touch LATEST-IS-${BRANCH}-${DATE}
+  rm -f LATEST-IS-${BRANCH}-${LAST_DATE}
+
+  inform "Sending mail"
+
+  export QMAILHOST=gcc.gnu.org
+  mail -s "gcc-ss-${RELEASE} is now available" gcc@gcc.gnu.org < ~ftp/pub/gcc/snapshots/${RELEASE}/README
 }
 
 ########################################################################
@@ -380,8 +458,13 @@ RELEASE_REVISION=""
 # The complete name of the release.
 RELEASE=""
 
-# The name of the branch from which the release should be made.
+# The name of the branch from which the release should be made, in a 
+# user-friendly form.
 BRANCH=""
+
+# The name of the branch from which the release should be made, as used
+# for our version control system.
+CVSBRANCH=""
 
 # The tag to apply to the sources used for the release.
 TAG=""
@@ -418,13 +501,13 @@ SNAPSHOT=0
 LOCAL=0
 
 # Major operation modes.
-MODE_BZIP2=0
+MODE_GZIP=0
 MODE_DIFFS=0
 MODE_SOURCES=0
 MODE_TARFILES=0
 MODE_UPLOAD=0
 
-# .gz files generated to create .bz2 files from.
+# List of archive files generated; used to create .gz files from .bz2.
 FILE_LIST=""
 
 # Programs we use.
@@ -443,14 +526,17 @@ TAR="${TAR:-tar}"
 ########################################################################
 
 # Parse the options.
-while getopts "d:fr:u:t:p:sl" ARG; do
+while getopts "d:fr:u:t:p:s:l" ARG; do
     case $ARG in
     d)    DESTINATION="${OPTARG}";;
     r)    RELEASE="${OPTARG}";;
     t)    TAG="${OPTARG}";;
     u)    CVS_USERNAME="${OPTARG}";;
     f)    FINAL=1;;
-    s)    SNAPSHOT=1;;
+    s)    SNAPSHOT=1
+          BRANCH=${OPTARG%:*}
+          CVSBRANCH=${OPTARG#*:}
+          ;;
     l)    LOCAL=1
 	  SCP=cp
 	  FTP_PATH=~ftp/pub/gcc
@@ -463,6 +549,25 @@ while getopts "d:fr:u:t:p:sl" ARG; do
     esac
 done
 shift `expr ${OPTIND} - 1`
+
+# Handle the major modes.
+while [ $# -ne 0 ]; do
+    case $1 in
+    diffs)    MODE_DIFFS=1;;
+    gzip)     MODE_GZIP=1;;
+    sources)  MODE_SOURCES=1;;
+    tarfiles) MODE_TARFILES=1;;
+    upload)   MODE_UPLOAD=1;;
+    all)      MODE_SOURCES=1; MODE_TARFILES=1; MODE_DIFFS=1; MODE_UPLOAD=1;
+              if [ $SNAPSHOT -ne 1 ]; then
+                # Only for releases and pre-releases.
+                MODE_GZIP=1;
+              fi
+              ;;
+    *)        error "Unknown mode $1";;
+    esac
+    shift
+done
 
 # Perform consistency checking.
 if [ ${LOCAL} -eq 0 ] && [ -z ${CVS_USERNAME} ]; then
@@ -496,29 +601,28 @@ if [ $SNAPSHOT -eq 0 ]; then
 
   # Compute the name of the branch, which is based solely on the major
   # and minor release numbers.
-  BRANCH="gcc-${RELEASE_MAJOR}_${RELEASE_MINOR}-branch"
+  CVSBRANCH="gcc-${RELEASE_MAJOR}_${RELEASE_MINOR}-branch"
 
   # If this is not a final release, set various parameters acordingly.
   if [ ${FINAL} -ne 1 ]; then
     RELEASE="${RELEASE}-${DATE}"
-    FTP_PATH="${FTP_PATH}/snapshots/"
+    FTP_PATH="${FTP_PATH}/prerelease-${RELEASE}/"
   else
     FTP_PATH="${FTP_PATH}/releases/gcc-${RELEASE}/"
   fi
 else
-  RELEASE=$DATE
-  # For now snapshots come from the mainline.
-  BRANCH=HEAD
-  FTP_PATH="${FTP_PATH}/snapshots/${LONG_DATE}"
-  TAG=gcc_ss_${DATE}
+  RELEASE=${BRANCH}-${DATE}
+  FTP_PATH="${FTP_PATH}/snapshots/${RELEASE}"
+  if [ ${CVSBRANCH} != "HEAD" ]; then
+    TAG=gcc-ss-`echo ${RELEASE} | tr '.' '_'`
+  fi
 
   # Building locally on gcc.gnu.org, we know what the last snapshot date
   # was.
-  if [ $LOCAL -ne 0 ]; then
-    LAST_DATE=`cat ~/.snapshot_date`
-    LAST_LONG_DATE=`date --date=$LAST_DATE +%Y-%m-%d`
-    LAST_DIR=~ftp/pub/gcc/snapshots/${LAST_LONG_DATE}
-    OLD_TARS=${LAST_DIR}/gcc-${LAST_DATE}.tar.gz
+  if [ $MODE_DIFFS -ne 0 ] && [ $LOCAL -ne 0 ]; then
+    LAST_DATE=`cat ~/.snapshot_date-${BRANCH}`
+    LAST_DIR=~ftp/pub/gcc/snapshots/${BRANCH}-${LAST_DATE}
+    OLD_TARS=${LAST_DIR}/gcc-${BRANCH}-${LAST_DATE}.tar.bz2
   fi
 fi
 
@@ -552,20 +656,6 @@ export CVSROOT
 TZ="UTC0"
 export TZ
 
-# Handle the major modes.
-while [ $# -ne 0 ]; do
-    case $1 in
-    bzip2)    MODE_BZIP2=1;;
-    diffs)    MODE_DIFFS=1;;
-    sources)  MODE_SOURCES=1;;
-    tarfiles) MODE_TARFILES=1;;
-    upload)   MODE_UPLOAD=1;;
-    all)      MODE_SOURCES=1; MODE_TARFILES=1; MODE_DIFFS=1; MODE_BZIP2=1; MODE_UPLOAD=1;;
-    *)        error "Unknown mode $1";;
-    esac
-    shift
-done
-
 # Build the source directory.
 
 if [ $MODE_SOURCES -ne 0 ]; then
@@ -589,9 +679,9 @@ if [ $MODE_DIFFS -ne 0 ]; then
   fi
 fi
 
-# Build bzip2 files
-if [ $MODE_BZIP2 -ne 0 ]; then
-  build_bzip2
+# Build gzip files
+if [ $MODE_GZIP -ne 0 ]; then
+  build_gzip
 fi
 
 # Upload them to the FTP server.
@@ -601,32 +691,11 @@ if [ $MODE_UPLOAD -ne 0 ]; then
 
   # For snapshots, make some further updates.
   if [ $SNAPSHOT -ne 0 ] && [ $LOCAL -ne 0 ]; then
-    # Update links on the FTP server.
-    TEXT_DATE=`date --date=$DATE +%B\ %d,\ %Y`
-    cd ~ftp/pub/gcc/snapshots
-    sed -e "s%@DATE@%$DATE%g" -e "s%@LAST_DATE@%$LAST_DATE%g" \
-      -e "s%@LONG_DATE@%$LONG_DATE%g" \
-      -e "s%@TEXT_DATE@%$TEXT_DATE%g" < ~/scripts/snapshot-README > $$
-    mv $$ README
-    sed -e "s%@DATE@%$DATE%g" -e "s%@LAST_DATE@%$LAST_DATE%g" \
-      -e "s%@LONG_DATE@%$LONG_DATE%g" \
-      -e "s%@TEXT_DATE@%$TEXT_DATE%g" < ~/scripts/snapshot-index.html > $$
-    mv $$ index.html
-
-    touch LATEST-IS-$LONG_DATE
-    rm -f LATEST-IS-$LAST_LONG_DATE
+    announce_snapshot
 
     # Update snapshot date file.
     changedir ~
-    echo $DATE >.snapshot_date
-
-    # Update gcc_latest_snapshot tag.
-    ${CVS} rtag -d gcc_latest_snapshot gcc
-    ${CVS} rtag -rgcc_ss_${DATE} gcc_latest_snapshot gcc
-
-    # Announce the snapshot.
-    export QMAILHOST=gcc.gnu.org
-    mail -s "gcc-ss-$DATE is now available" gcc@gcc.gnu.org < ~ftp/pub/gcc/snapshots/README
+    echo $DATE > .snapshot_date-${BRANCH}
 
     # Remove working directory
     rm -rf ${WORKING_DIRECTORY}
