Release branch only commit: Add --with-multi-buildlist to config-ml.in
Add a new option that allows build time selection of multilibs based
on a file containing one multilib directory per line.

diff --git a/config-ml.in b/config-ml.in
--- a/config-ml.in
+++ b/config-ml.in
@@ -374,6 +374,23 @@ mips*-*-*)
 	    esac
 	  done
 	fi
+	if [ x$with_multi_buildlist != x ]
+	then
+	  old_multidirs="${multidirs}"
+	  if [ ! -f $with_multi_buildlist ]
+	  then
+	    echo "config-ml.in: Failed to find $with_multi_buildlist"
+	    exit 1
+	  fi
+	  multidirs=""
+	  for x in ${old_multidirs}; do
+	    found=`grep "^${x}$" $with_multi_buildlist`
+	    if [ -n "$found" ]
+	    then
+	      multidirs="${multidirs} ${x}"
+	    fi
+	  done
+	fi
 	;;
 powerpc*-*-* | rs6000*-*-*)
 	if [ x$enable_aix64 = xno ]
