* configure.in: Handle stage1_languages properly. 	* configure: Regenerate. 	Auto-detects ada for stage 1 now, and bootstraps!
	Merge from mainline.


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/toplevel-bootstrap@68596 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -136,7 +136,7 @@ libgcj="target-libffi \
 # these libraries are built for the target environment, and are built after
 # the host libraries and the host tools (which may be a cross compiler)
 #
-target_libs="target-libiberty \
+target_libraries="target-libiberty \
 		target-libgloss \
 		target-newlib \
 		target-libstdc++-v3 \
@@ -144,10 +144,10 @@ target_libs="target-libiberty \
 		${libgcj} \
 		target-libobjc"
 
-# these tools are built using the target libs, and are intended to run only
-# in the target environment
+# these tools are built using the target libraries, and are intended to
+# run only in the target environment
 #
-# note: any program that *uses* libraries that are in the "target_libs"
+# note: any program that *uses* libraries that are in the "target_libraries"
 # list belongs in this list.  those programs are also very likely
 # candidates for the "native_only" list which follows
 #
@@ -162,7 +162,7 @@ target_tools="target-examples target-groff target-gperf target-rda"
 ## ${target_configdirs} is directories we build using the target tools.
 #
 configdirs=`echo ${host_libs} ${host_tools}`
-target_configdirs=`echo ${target_libs} ${target_tools}`
+target_configdirs=`echo ${target_libraries} ${target_tools}`
 
 # Modules which run on the build machine.
 build_modules="libiberty gcc"
@@ -445,22 +445,22 @@ case "${target}" in
     noconfigdirs="$noconfigdirs target-libstdc++-v3 target-libgloss ${libgcj} gcc gdb newlib"
     ;;
   cris-*-*)
-    noconfigdirs="$noconfigdirs ${libgcj}"
+    noconfigdirs="$noconfigdirs ${libgcj} target-newlib target-libgloss"
     ;;
   d10v-*-*)
     noconfigdirs="$noconfigdirs target-libstdc++-v3 target-libgloss ${libgcj}"
     ;;
   d30v-*-*)
-    noconfigdirs="$noconfigdirs ${libgcj}"
+    noconfigdirs="$noconfigdirs ${libgcj} gdb"
     ;;
   fr30-*-elf*)
-    noconfigdirs="$noconfigdirs ${libgcj}"
+    noconfigdirs="$noconfigdirs ${libgcj} gdb"
     ;;
   frv-*-*)
     noconfigdirs="$noconfigdirs ${libgcj}"
     ;;
   h8300*-*-*)
-    noconfigdirs="$noconfigdirs target-libgloss"
+    noconfigdirs="$noconfigdirs target-libgloss ${libgcj} target-libf2c"
     ;;
   h8500-*-*)
     noconfigdirs="$noconfigdirs target-libstdc++-v3 target-libgloss ${libgcj} target-libf2c"
@@ -483,6 +483,9 @@ case "${target}" in
     # According to Alexandre Oliva <aoliva@redhat.com>, libjava won't
     # build on HP-UX 10.20.
     noconfigdirs="$noconfigdirs ld shellutils ${libgcj}"
+    ;;
+  i960-*-*)
+    noconfigdirs="$noconfigdirs ${libgcj} gdb"
     ;;
   ia64*-*-elf*)
     # No gdb support yet.
@@ -560,6 +563,9 @@ case "${target}" in
     ;;
   i[[3456789]]86-*-beos*)
     noconfigdirs="$noconfigdirs gdb target-newlib target-libgloss ${libgcj}"
+    ;;
+  m32r-*-*)
+    noconfigdirs="$noconfigdirs ${libgcj} gdb"
     ;;
   m68hc11-*-*|m6811-*-*|m68hc12-*-*|m6812-*-*)
     noconfigdirs="$noconfigdirs target-libiberty target-libstdc++-v3 ${libgcj}"
@@ -740,24 +746,24 @@ enable_languages=`echo "${enable_languages}" | sed -e 's/[[ 	,]][[ 	,]]*/,/g' -e
 # First scan to see if an enabled language requires some other language.
 # We assume that a given config-lang.in will list all the language
 # front ends it requires, even if some are required indirectly.
-for lang in ${srcdir}/gcc/*/config-lang.in ..
-do
-  case $lang in
+for lang_frag in ${srcdir}/gcc/*/config-lang.in .. ; do
+  case ${lang_frag} in
     ..) ;;
     # The odd quoting in the next line works around
     # an apparent bug in bash 1.12 on linux.
     ${srcdir}/gcc/[[*]]/config-lang.in) ;;
     *)
-      lang_alias=`sed -n -e 's,^language=[['"'"'"'"]]\(.*\)[["'"'"'"']].*$,\1,p' -e 's,^language=\([[^ 	]]*\).*$,\1,p' $lang`
-      this_lang_requires=`sed -n -e 's,^lang_requires=[['"'"'"'"]]\(.*\)[["'"'"'"']].*$,\1,p' -e 's,^lang_requires=\([[^ 	]]*\).*$,\1,p' $lang`
-      for other in $this_lang_requires
-      do
+      # From the config-lang.in, get $language, $lang_requires
+      language=
+      lang_requires=
+      . ${lang_frag}
+      for other in ${lang_requires} ; do
         case ,${enable_languages}, in
 	  *,$other,*) ;;
 	  *,all,*) ;;
-	  *,$lang_alias,*)
-	    echo " \`$other' language required by \`$lang_alias'; enabling" 1>&2
-	    enable_languages="$enable_languages,$other"
+	  *,$language,*)
+	    echo " \`$other' language required by \`$language'; enabling" 1>&2
+	    enable_languages="${enable_languages},${other}"
 	    ;;
 	esac
       done
@@ -765,35 +771,57 @@ do
   esac
 done
 
-subdirs=
-for lang in ${srcdir}/gcc/*/config-lang.in ..
-do
-  case $lang in
+# By default, only C is a stage 1 language.
+stage1_languages=c
+AC_SUBST(stage1_languages)
+
+for lang_frag in ${srcdir}/gcc/*/config-lang.in .. ; do
+  case ${lang_frag} in
     ..) ;;
     # The odd quoting in the next line works around
     # an apparent bug in bash 1.12 on linux.
     ${srcdir}/gcc/[[*]]/config-lang.in) ;;
     *)
-      lang_alias=`sed -n -e 's,^language=[['"'"'"'"]]\(.*\)[["'"'"'"']].*$,\1,p' -e 's,^language=\([[^ 	]]*\).*$,\1,p' $lang`
-      this_lang_libs=`sed -n -e 's,^target_libs=[['"'"'"'"]]\(.*\)[["'"'"'"']].*$,\1,p' -e 's,^target_libs=\([[^ 	]]*\).*$,\1,p' $lang`
-      this_lang_dirs=`sed -n -e 's,^lang_dirs=[['"'"'"'"]]\(.*\)[["'"'"'"']].*$,\1,p' -e 's,^lang_dirs=\([[^ 	]]*\).*$,\1,p' $lang`
-      build_by_default=`sed -n -e 's,^build_by_default=[['"'"'"'"]]\(.*\)[["'"'"'"']].*$,\1,p' -e 's,^build_by_default=\([[^ 	]]*\).*$,\1,p' $lang`
-      if test "x$lang_alias" = x
-         then
-        echo "$lang doesn't set \$language." 1>&2
+      # From the config-lang.in, get $language, $target_libs, 
+      # $lang_dirs, $boot_language, and $build_by_default
+      language=
+      target_libs=
+      lang_dirs=
+      boot_language=
+      build_by_default=
+      . ${lang_frag}
+      if test "x$language" = x ; then
+        echo "${lang_frag} doesn't set \$language." 1>&2
         exit 1
       fi
-      case ${build_by_default},${enable_languages}, in
-        *,$lang_alias,*) add_this_lang=yes ;;
-        no,*) add_this_lang=no ;;
-        *,all,*) add_this_lang=yes ;;
+      case ,${enable_languages}, in
+        *,${language},*)
+          # Language was explicitly selected; include it.
+          add_this_lang=yes
+          ;;
+        *,all,*)
+          # 'all' was selected; include 'default' languages.
+          case ${build_by_default} in
+            no) add_this_lang=no ;;
+            *) add_this_lang=yes ;;
+          esac 
+          ;;
         *) add_this_lang=no ;;
       esac
-      if test x"${add_this_lang}" = xyes; then
-        eval target_libs='"$target_libs "'\"$this_lang_libs\"
-      else
-        eval noconfigdirs='"$noconfigdirs "'\"$this_lang_libs $this_lang_dirs\"
-      fi
+      case ${add_this_lang} in
+        yes)
+          case ${boot_language} in
+            yes)
+              # Add to (space-separated) list of stage 1 languages.
+              stage1_languages="${stage1_languages} ${language}"
+              ;;
+          esac
+          ;;
+        no)
+          # Remove language-dependent dirs.
+          eval noconfigdirs='"$noconfigdirs "'\"$target_libs $lang_dirs\"
+          ;;
+      esac
       ;;
   esac
 done
@@ -1899,7 +1927,7 @@ fi
 GCJ_FOR_TARGET=$GCJ_FOR_TARGET' $(FLAGS_FOR_TARGET)'
 
 # Don't use libstdc++-v3's flags to configure/build itself.
-libstdcxx_flags='`test ! -f $$r/$(TARGET_SUBDIR)/libstdc++-v3/testsuite_flags || $(SHELL) $$r/$(TARGET_SUBDIR)/libstdc++-v3/testsuite_flags --build-includes` -L$$r/$(TARGET_SUBDIR)/libstdc++-v3/src -L$$r/$(TARGET_SUBDIR)/libstdc++-v3/src/.libs'
+libstdcxx_flags='`test ! -f $$r/$(TARGET_SUBDIR)/libstdc++-v3/scripts/testsuite_flags || $(SHELL) $$r/$(TARGET_SUBDIR)/libstdc++-v3/scripts/testsuite_flags --build-includes` -L$$r/$(TARGET_SUBDIR)/libstdc++-v3/src -L$$r/$(TARGET_SUBDIR)/libstdc++-v3/src/.libs'
 raw_libstdcxx_flags=' -L$$r/$(TARGET_SUBDIR)/libstdc++-v3/src -L$$r/$(TARGET_SUBDIR)/libstdc++-v3/src/.libs'
 
 if test "x${CXX_FOR_TARGET+set}" = xset; then
@@ -2084,10 +2112,6 @@ case $build in
     ;;
 esac
 AC_SUBST(stage1_cflags)
-
-# FIXME: This needs to be done much better.  Sadly, that's hairy.
-stage1_languages="c ada"
-AC_SUBST(stage1_languages)
 
 # Enable -Werror in bootstrap stage2 and later.
 # Change the default to "no" on release branches.
diff --git a/maintainer-scripts/gcc_release b/maintainer-scripts/gcc_release
--- a/maintainer-scripts/gcc_release
+++ b/maintainer-scripts/gcc_release
@@ -245,11 +245,11 @@ EOF
 
 build_tarfile() {
   # Get the name of the destination tar file.
-  TARFILE="$1.tar.gz"
+  TARFILE="$1.tar.bz2"
   shift
 
   # Build the tar file itself.
-  (${TAR} cf - "$@" | ${GZIP} > ${TARFILE}) || \
+  (${TAR} cf - "$@" | ${BZIP2} > ${TARFILE}) || \
     error "Could not build tarfile"
   FILE_LIST="${FILE_LIST} ${TARFILE}"
 }
@@ -288,11 +288,11 @@ build_tarfiles() {
     `basename ${SOURCE_DIRECTORY}`
 }
 
-# Build .bz2 files.
-build_bzip2() {
+# Build .gz files.
+build_gzip() {
   for f in ${FILE_LIST}; do
-    bzfile=${f%.gz}.bz2
-    (zcat $f | ${BZIP2} > ${bzfile}) || error "Could not create ${bzfile}"
+    target=${f%.bz2}.gz
+    (${BZIP2} -d -c $f | ${GZIP} > ${target}) || error "Could not create ${target}"
   done
 }
 
@@ -300,19 +300,19 @@ build_bzip2() {
 build_diffs() {
   old_dir=${1%/*}
   old_file=${1##*/}
-  old_vers=${old_file%.tar.gz}
+  old_vers=${old_file%.tar.bz2}
   old_vers=${old_vers#gcc-}
   inform "Building diffs against version $old_vers"
   for f in gcc gcc-ada gcc-g++ gcc-g77 gcc-java gcc-objc gcc-testsuite gcc-core; do
-    old_tar=${old_dir}/${f}-${old_vers}.tar.gz
-    new_tar=${WORKING_DIRECTORY}/${f}-${RELEASE}.tar.gz
+    old_tar=${old_dir}/${f}-${old_vers}.tar.bz2
+    new_tar=${WORKING_DIRECTORY}/${f}-${RELEASE}.tar.bz2
     if [ ! -e $old_tar ]; then
       inform "$old_tar not found; not generating diff file"
     elif [ ! -e $new_tar ]; then
       inform "$new_tar not found; not generating diff file"
     else
       build_diff $old_tar gcc-${old_vers} $new_tar gcc-${RELEASE} \
-        ${f}-${old_vers}-${RELEASE}.diff.gz
+        ${f}-${old_vers}-${RELEASE}.diff.bz2
     fi
   done
 }
@@ -323,20 +323,19 @@ build_diff() {
   tmpdir=gccdiff.$$
   mkdir $tmpdir || error "Could not create directory $tmpdir"
   changedir $tmpdir
-  ${TAR} xfz $1 || error "Could not unpack $1 for diffs"
-  ${TAR} xfz $3 || error "Could not unpack $3 for diffs"
-  ${DIFF} $2 $4 > ../${5%.gz}
+  (${BZIP2} -d -c $1 | ${TAR} xf - ) || error "Could not unpack $1 for diffs"
+  (${BZIP2} -d -c $3 | ${TAR} xf - ) || error "Could not unpack $3 for diffs"
+  ${DIFF} $2 $4 > ../${5%.bz2}
   if [ $? -eq 2 ]; then
     error "Trouble making diffs from $1 to $3"
   fi
-  ${GZIP} ../${5%.gz} || error "Could not gzip ../${5%.gz}"
+  ${BZIP2} ../${5%.bz2} || error "Could not generate ../$5"
   changedir ..
   rm -rf $tmpdir
   FILE_LIST="${FILE_LIST} $5"
 }
 
 # Upload the files to the FTP server.
-
 upload_files() {
   inform "Uploading files"
 
@@ -370,6 +369,30 @@ upload_files() {
         || error "Could not upload ${x}"
     fi
   done
+}
+
+# Announce a snapshot, both on the web and via mail.
+announce_snapshot() {
+  inform "Updating links and READMEs on the FTP server"
+  
+  TEXT_DATE=`date --date=$DATE +%B\ %d,\ %Y`
+  cd ~ftp/pub/gcc/snapshots
+  sed -e "s%@DATE@%$DATE%g" -e "s%@LAST_DATE@%$LAST_DATE%g" \
+    -e "s%@LONG_DATE@%$LONG_DATE%g" \
+    -e "s%@TEXT_DATE@%$TEXT_DATE%g" < ~/scripts/snapshot-README > $$
+  mv $$ README
+  sed -e "s%@DATE@%$DATE%g" -e "s%@LAST_DATE@%$LAST_DATE%g" \
+    -e "s%@LONG_DATE@%$LONG_DATE%g" \
+    -e "s%@TEXT_DATE@%$TEXT_DATE%g" < ~/scripts/snapshot-index.html > $$
+  mv $$ index.html
+
+  touch LATEST-IS-$LONG_DATE
+  rm -f LATEST-IS-$LAST_LONG_DATE
+
+  inform "Sending mail"
+
+  export QMAILHOST=gcc.gnu.org
+  mail -s "gcc-ss-$DATE is now available" gcc@gcc.gnu.org < ~ftp/pub/gcc/snapshots/README
 }
 
 ########################################################################
@@ -446,13 +469,13 @@ SNAPSHOT=0
 LOCAL=0
 
 # Major operation modes.
-MODE_BZIP2=0
+MODE_GZIP=0
 MODE_DIFFS=0
 MODE_SOURCES=0
 MODE_TARFILES=0
 MODE_UPLOAD=0
 
-# .gz files generated to create .bz2 files from.
+# List of archive files generated; used to create .gz files from .bz2.
 FILE_LIST=""
 
 # Programs we use.
@@ -546,7 +569,7 @@ else
     LAST_DATE=`cat ~/.snapshot_date`
     LAST_LONG_DATE=`date --date=$LAST_DATE +%Y-%m-%d`
     LAST_DIR=~ftp/pub/gcc/snapshots/${LAST_LONG_DATE}
-    OLD_TARS=${LAST_DIR}/gcc-${LAST_DATE}.tar.gz
+    OLD_TARS=${LAST_DIR}/gcc-${LAST_DATE}.tar.bz2
   fi
 fi
 
@@ -583,12 +606,12 @@ export TZ
 # Handle the major modes.
 while [ $# -ne 0 ]; do
     case $1 in
-    bzip2)    MODE_BZIP2=1;;
     diffs)    MODE_DIFFS=1;;
+    gzip)     MODE_GZIP=1;;
     sources)  MODE_SOURCES=1;;
     tarfiles) MODE_TARFILES=1;;
     upload)   MODE_UPLOAD=1;;
-    all)      MODE_SOURCES=1; MODE_TARFILES=1; MODE_DIFFS=1; MODE_BZIP2=1; MODE_UPLOAD=1;;
+    all)      MODE_SOURCES=1; MODE_TARFILES=1; MODE_DIFFS=1; MODE_GZIP=1; MODE_UPLOAD=1;;
     *)        error "Unknown mode $1";;
     esac
     shift
@@ -617,9 +640,9 @@ if [ $MODE_DIFFS -ne 0 ]; then
   fi
 fi
 
-# Build bzip2 files
-if [ $MODE_BZIP2 -ne 0 ]; then
-  build_bzip2
+# Build gzip files
+if [ $MODE_GZIP -ne 0 ]; then
+  build_gzip
 fi
 
 # Upload them to the FTP server.
@@ -629,32 +652,11 @@ if [ $MODE_UPLOAD -ne 0 ]; then
 
   # For snapshots, make some further updates.
   if [ $SNAPSHOT -ne 0 ] && [ $LOCAL -ne 0 ]; then
-    # Update links on the FTP server.
-    TEXT_DATE=`date --date=$DATE +%B\ %d,\ %Y`
-    cd ~ftp/pub/gcc/snapshots
-    sed -e "s%@DATE@%$DATE%g" -e "s%@LAST_DATE@%$LAST_DATE%g" \
-      -e "s%@LONG_DATE@%$LONG_DATE%g" \
-      -e "s%@TEXT_DATE@%$TEXT_DATE%g" < ~/scripts/snapshot-README > $$
-    mv $$ README
-    sed -e "s%@DATE@%$DATE%g" -e "s%@LAST_DATE@%$LAST_DATE%g" \
-      -e "s%@LONG_DATE@%$LONG_DATE%g" \
-      -e "s%@TEXT_DATE@%$TEXT_DATE%g" < ~/scripts/snapshot-index.html > $$
-    mv $$ index.html
-
-    touch LATEST-IS-$LONG_DATE
-    rm -f LATEST-IS-$LAST_LONG_DATE
+    announce_snapshot
 
     # Update snapshot date file.
     changedir ~
     echo $DATE >.snapshot_date
-
-    # Update gcc_latest_snapshot tag.
-    ${CVS} rtag -d gcc_latest_snapshot gcc
-    ${CVS} rtag -rgcc_ss_${DATE} gcc_latest_snapshot gcc
-
-    # Announce the snapshot.
-    export QMAILHOST=gcc.gnu.org
-    mail -s "gcc-ss-$DATE is now available" gcc@gcc.gnu.org < ~ftp/pub/gcc/snapshots/README
 
     # Remove working directory
     rm -rf ${WORKING_DIRECTORY}
