* Makefile.tpl: Add rudimentary bootstrap support.  Rip out 	old bootstrap targets. 	* Makefile.def: Comment out build-gcc, for now. 	* Makefile.in: Regenerate. 	* configure.in: Add some bootstrap support stuff, originally 	from gcc/configure.in. 	* configure: Regenerate.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/toplevel-bootstrap@68063 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -17680,75 +17680,6 @@ all-build-libiberty: configure-build-libiberty
 	s=`cd $(srcdir); ${PWD}`; export s; \
 	(cd $(BUILD_SUBDIR)/libiberty && $(MAKE)  all)
 
-.PHONY: configure-build-gcc maybe-configure-build-gcc
-maybe-configure-build-gcc:
-configure-build-gcc:
-	@test ! -f $(BUILD_SUBDIR)/gcc/Makefile || exit 0; \
-	[ -d $(BUILD_SUBDIR)/gcc ] || \
-	  mkdir $(BUILD_SUBDIR)/gcc;\
-	r=`${PWD}`; export r; \
-	s=`cd $(srcdir); ${PWD}`; export s; \
-	AR="$(AR_FOR_BUILD)"; export AR; \
-	AS="$(AS_FOR_BUILD)"; export AS; \
-	CC="$(CC_FOR_BUILD)"; export CC; \
-	CFLAGS="$(CFLAGS_FOR_BUILD)"; export CFLAGS; \
-	CXX="$(CXX_FOR_BUILD)"; export CXX; \
-	CXXFLAGS="$(CXXFLAGS_FOR_BUILD)"; export CXXFLAGS; \
-	GCJ="$(GCJ_FOR_BUILD)"; export GCJ; \
-	DLLTOOL="$(DLLTOOL_FOR_BUILD)"; export DLLTOOL; \
-	LD="$(LD_FOR_BUILD)"; export LD; \
-	LDFLAGS="$(LDFLAGS_FOR_BUILD)"; export LDFLAGS; \
-	NM="$(NM_FOR_BUILD)"; export NM; \
-	RANLIB="$(RANLIB_FOR_BUILD)"; export RANLIB; \
-	WINDRES="$(WINDRES_FOR_BUILD)"; export WINDRES; \
-	echo Configuring in $(BUILD_SUBDIR)/gcc; \
-	cd "$(BUILD_SUBDIR)/gcc" || exit 1; \
-	case $(srcdir) in \
-	  /* | [A-Za-z]:[\\/]*) \
-	    topdir=$(srcdir) ;; \
-	  *) \
-	    case "$(BUILD_SUBDIR)" in \
-	      .) topdir="../$(srcdir)" ;; \
-	      *) topdir="../../$(srcdir)" ;; \
-	    esac ;; \
-	esac; \
-	if [ "$(srcdir)" = "." ] ; then \
-	  if [ "$(BUILD_SUBDIR)" != "." ] ; then \
-	    if $(SHELL) $$s/symlink-tree $${topdir}/gcc "no-such-file" ; then \
-	      if [ -f Makefile ]; then \
-	        if $(MAKE) distclean; then \
-	          true; \
-	        else \
-	          exit 1; \
-	        fi; \
-	      else \
-	        true; \
-	      fi; \
-	    else \
-	      exit 1; \
-	    fi; \
-	  else \
-	    true; \
-	  fi; \
-	  srcdiroption="--srcdir=."; \
-	  libsrcdir="."; \
-	else \
-	  srcdiroption="--srcdir=$${topdir}/gcc"; \
-	  libsrcdir="$$s/gcc"; \
-	fi; \
-	rm -f no-such-file || : ; \
-	CONFIG_SITE=no-such-file $(SHELL) $${libsrcdir}/configure \
-	  $(BUILD_CONFIGARGS) $${srcdiroption} \
-	  --with-build-subdir="$(BUILD_SUBDIR)"  \
-	  || exit 1
-
-.PHONY: all-build-gcc maybe-all-build-gcc
-maybe-all-build-gcc:
-all-build-gcc: configure-build-gcc
-	@r=`${PWD}`; export r; \
-	s=`cd $(srcdir); ${PWD}`; export s; \
-	(cd $(BUILD_SUBDIR)/gcc && $(MAKE) LANGUAGES="$(BOOT_LANGUAGES)" CFLAGS="$(STAGE1_CFLAGS)" COVERAGE_FLAGS=  all)
-
 
 # --------------------------------------
 # Modules which run on the host machine
@@ -23663,66 +23594,6 @@ all-gcc: configure-gcc
 	  (cd gcc && $(MAKE) $(GCC_FLAGS_TO_PASS) all); \
 	fi
 
-# Building GCC uses some tools for rebuilding "source" files
-# like texinfo, bison/byacc, etc.  So we must depend on those.
-#
-# While building GCC, it may be necessary to run various target
-# programs like the assembler, linker, etc.  So we depend on
-# those too.
-#
-# In theory, on an SMP all those dependencies can be resolved
-# in parallel.
-#
-GCC_STRAP_TARGETS = bootstrap bootstrap-lean bootstrap2 bootstrap2-lean bootstrap3 bootstrap3-lean bootstrap4 bootstrap4-lean bubblestrap quickstrap cleanstrap restrap
-.PHONY: $(GCC_STRAP_TARGETS)
-$(GCC_STRAP_TARGETS): all-bootstrap configure-gcc
-	@r=`${PWD}`; export r; \
-	s=`cd $(srcdir); ${PWD}`; export s; \
-	$(SET_LIB_PATH) \
-	echo "Bootstrapping the compiler"; \
-	cd gcc && $(MAKE) $(GCC_FLAGS_TO_PASS) $@
-	@r=`${PWD}`; export r; \
-	s=`cd $(srcdir); ${PWD}`; export s; \
-	case "$@" in \
-	  *bootstrap4-lean ) \
-	    msg="Comparing stage3 and stage4 of the compiler"; \
-	    compare=compare3-lean ;; \
-	  *bootstrap4 ) \
-	    msg="Comparing stage3 and stage4 of the compiler"; \
-	    compare=compare3 ;; \
-	  *-lean ) \
-	    msg="Comparing stage2 and stage3 of the compiler"; \
-	    compare=compare-lean ;; \
-	  * ) \
-	    msg="Comparing stage2 and stage3 of the compiler"; \
-	    compare=compare ;; \
-	esac; \
-	$(SET_LIB_PATH) \
-	echo "$$msg"; \
-	cd gcc && $(MAKE) $(GCC_FLAGS_TO_PASS) $$compare
-	@r=`${PWD}`; export r; \
-	s=`cd $(srcdir); ${PWD}` ; export s; \
-	$(SET_LIB_PATH) \
-	echo "Building runtime libraries"; \
-	$(MAKE) $(BASE_FLAGS_TO_PASS) $(RECURSE_FLAGS) all
-
-profiledbootstrap: all-bootstrap configure-gcc
-	@r=`${PWD}`; export r; \
-	s=`cd $(srcdir); ${PWD}`; export s; \
-	$(SET_LIB_PATH) \
-	echo "Bootstrapping the compiler"; \
-	cd gcc && $(MAKE) $(GCC_FLAGS_TO_PASS) stageprofile_build
-	@r=`${PWD}`; export r; \
-	s=`cd $(srcdir); ${PWD}` ; export s; \
-	$(SET_LIB_PATH) \
-	echo "Building runtime libraries and training compiler"; \
-	$(MAKE) $(BASE_FLAGS_TO_PASS) $(RECURSE_FLAGS) all
-	@r=`${PWD}`; export r; \
-	s=`cd $(srcdir); ${PWD}`; export s; \
-	$(SET_LIB_PATH) \
-	echo "Building feedback based compiler"; \
-	cd gcc && $(MAKE) $(GCC_FLAGS_TO_PASS) stagefeedback_build
-
 .PHONY: cross
 cross: all-texinfo all-bison all-byacc all-binutils all-gas all-ld
 	@r=`${PWD}`; export r; \
@@ -23796,6 +23667,104 @@ gcc-no-fixedincludes:
 	  rm -rf gcc/include; \
 	  mv gcc/tmp-include gcc/include 2>/dev/null; \
 	else true; fi
+
+# ---------------------
+# GCC bootstrap support
+# ---------------------
+
+# 'touch' doesn't work right on some platforms.
+STAMP = echo timestamp >
+
+# Only build the C compiler for stage1, because that is the only one that
+# we can guarantee will build with the native compiler, and also it is the
+# only thing useful for building stage2. STAGE1_CFLAGS (via CFLAGS),
+# MAKEINFO and MAKEINFOFLAGS are explicitly passed here to make them
+# overrideable (for a bootstrap build stage1 also builds gcc.info).
+
+STAGE1_CFLAGS=@stage1_cflags@
+
+stage1_build: all-bootstrap
+	r=`${PWD}`; export r; \
+	s=`cd $(srcdir); ${PWD}`; export s; \
+	$(MAKE) configure-gcc
+	r=`${PWD}`; export r; \
+	s=`cd $(srcdir); ${PWD}`; export s; \
+	cd gcc && \
+	$(MAKE) $(GCC_FLAGS_TO_PASS) \
+                LANGUAGES="@stage1_languages@" \
+		CFLAGS="$(STAGE1_CFLAGS)" \
+		COVERAGE_FLAGS=
+	$(STAMP) stage1_build
+	echo stage1_build > stage_last
+
+stage1_copy: stage1_build
+	mv gcc stage1-gcc
+	$(STAMP) stage1_copy
+	echo stage2_build > stage_last
+
+# Flags to pass to stage2 and later makes.
+BOOT_CFLAGS= -g -O2
+POSTSTAGE1_FLAGS_TO_PASS = \
+	CFLAGS="$(BOOT_CFLAGS)" \
+	ADAC="\$$(CC)" \
+	WARN_CFLAGS="\$$(GCC_WARN_CFLAGS)" \
+	STRICT_WARN="\$$(STRICT2_WARN)" \
+	OUTPUT_OPTION="-o \$$@" \
+	WERROR="@WERROR@"
+
+stage2_build: stage1_copy
+	r=`${PWD}`; export r; \
+	s=`cd $(srcdir); ${PWD}`; export s; \
+	$(MAKE) configure-gcc
+	r=`${PWD}`; export r; \
+	s=`cd $(srcdir); ${PWD}`; export s; \
+	cd gcc && \
+	$(MAKE) $(GCC_FLAGS_TO_PASS) \
+		CC="$(STAGE_CC_WRAPPER) ../stage1-gcc/xgcc$(exeext) -B../stage1-gcc/ -B$(build_tooldir)/bin/" \
+		BUILD_CC="$(STAGE_CC_WRAPPER) ../stage1-gcc/xgcc$(exeext) -B../stage1-gcc/ -B$(build_tooldir)/bin/" \
+		CC_FOR_BUILD="$(STAGE_CC_WRAPPER) ../stage1-gcc/xgcc$(exeext) -B../stage1-gcc/ -B$(build_tooldir)/bin/" \
+		STAGE_PREFIX=../stage1-gcc/ \
+		$(POSTSTAGE1_FLAGS_TO_PASS)
+	$(STAMP) stage2_build
+	echo stage2_build > stage_last
+
+stage2_copy: stage2_build
+	mv gcc stage2-gcc
+	$(STAMP) stage2_copy
+	echo stage3_build > stage_last
+
+stage3_build: stage2_copy
+	r=`${PWD}`; export r; \
+	s=`cd $(srcdir); ${PWD}`; export s; \
+	$(MAKE) configure-gcc
+	r=`${PWD}`; export r; \
+	s=`cd $(srcdir); ${PWD}`; export s; \
+	cd gcc && \
+	$(MAKE) $(GCC_FLAGS_TO_PASS) \
+		CC="$(STAGE_CC_WRAPPER) ../stage2-gcc/xgcc$(exeext) -B../stage2-gcc/ -B$(build_tooldir)/bin/" \
+		BUILD_CC="$(STAGE_CC_WRAPPER) ../stage2-gcc/xgcc$(exeext) -B../stage2-gcc/ -B$(build_tooldir)/bin/" \
+		CC_FOR_BUILD="$(STAGE_CC_WRAPPER) ../stage2-gcc/xgcc$(exeext) -B../stage2-gcc/ -B$(build_tooldir)/bin/" \
+		STAGE_PREFIX=../stage2-gcc/ \
+		$(POSTSTAGE1_FLAGS_TO_PASS)
+	$(STAMP) stage3_build
+	echo stage3_build > stage_last
+
+compare: stage3_build
+	-rm -f .bad_compare
+	cd gcc ; \
+	for file in *$(objext); do \
+	  cmp --ignore-initial=16 $$file ../stage2-gcc/$$file > /dev/null 2>&1; \
+	  test $$? -eq 1 && echo $$file differs >> .bad_compare || true; \
+	done
+	if [ -f .bad_compare ]; then \
+	  echo "Bootstrap comparison failure!"; \
+	  cat .bad_compare; \
+	  exit 1; \
+	else \
+	  true; \
+	fi
+
+bootstrap: compare
 
 # --------------------------------------
 # Dependencies between different modules
