* thumb.c: Deleted.  Move contents to ... * arm.c: ... here. * t-arm-aout, t-arm-coff, t-arm-elf, t-linux, t-netbsd, t-semi: Remove rule for thumb.o * configure.in (arm*-*-*): Remove thumb.o from extra_objs list. * configure: Regen.
* arm-protos.h: Use RTX_CODE and tidy up long lines.  Don't
declare a prototype for asm_output_align();

* arm.c (thumb_condition_code): Delete.
(arm_print_operand): Always use arm_condition_code array.

* arm.c (thumb_return_addr_rtx): Delete.
(arm_save_machine_status, arm_restore_machine_status): Delete.
(arm_init_machine_status, arm_mark_machine_status): New functions.
(arm_init_expanders): Update accordingly.
(arm_return_addr): Renamed from arm_return_addr_rtx.  Rewrite.
(thumb_expand_prologue): Delete code referencing thumb_return_addr_rtx.
* arm.h (RETURN_ADDR_RTX): Call arm_return_addr().


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/merged-arm-thumb-backend-branch@30194 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -3525,18 +3525,15 @@ for machine in $build $host $target; do
 	arm-*-coff* | armel-*-coff*)
 		tm_file=arm/coff.h
 		tmake_file=arm/t-arm-coff
-		extra_objs=thumb.o
 		;;
 	arm-*-vxworks*)
 		tm_file=arm/vxarm.h
 		tmake_file=arm/t-arm-coff
 		thread_file='vxworks'
-		extra_objs=thumb.o
 		;;
 	arm-*-riscix1.[01]*)		# Acorn RISC machine (early versions)
 		tm_file=arm/riscix1-1.h
 		use_collect2=yes
-		extra_objs=thumb.o
 		;;
 	arm-*-riscix*)			# Acorn RISC machine
 		if test x$gas = xyes
@@ -3548,24 +3545,20 @@ for machine in $build $host $target; do
 		xmake_file=arm/x-riscix
 		tmake_file=arm/t-riscix
 		use_collect2=yes
-		extra_objs=thumb.o
 		;;
 	arm-semi-aout | armel-semi-aout)
 		tm_file=arm/semi.h
 		tmake_file=arm/t-semi
-		extra_objs=thumb.o
 		;;
 	arm-semi-aof | armel-semi-aof)
 		tm_file=arm/semiaof.h
 		tmake_file=arm/t-semiaof
-		extra_objs=thumb.o
 		;;
 	arm*-*-netbsd*)
 		tm_file=arm/netbsd.h
 		xm_file="arm/xm-netbsd.h ${xm_file}"
 		tmake_file="t-netbsd arm/t-netbsd"
 		use_collect2=yes
-		extra_objs=thumb.o
 		;;
 	arm*-*-linux-gnuaout*)		# ARM GNU/Linux with a.out
 		cpu_type=arm
@@ -3573,7 +3566,6 @@ for machine in $build $host $target; do
 		tm_file=arm/linux-aout.h
 		tmake_file=arm/t-linux
 		gnu_ld=yes
-		extra_objs=thumb.o
 		;;
 	arm*-*-linux-gnuoldld*)		# ARM GNU/Linux with old ELF linker
 		xm_file=arm/xm-linux.h
@@ -3585,7 +3577,7 @@ for machine in $build $host $target; do
 			;;
 		esac
 		tmake_file="t-linux arm/t-linux"
-		extra_parts="crtbegin.o crtbeginS.o crtend.o crtendS.o thumb.o"
+		extra_parts="crtbegin.o crtbeginS.o crtend.o crtendS.o"
 		gnu_ld=yes
 		case x${enable_threads} in
 		x | xyes | xpthreads | xposix)
@@ -3603,7 +3595,7 @@ for machine in $build $host $target; do
 			;;
 		esac
 		tmake_file="t-linux arm/t-linux"
-		extra_parts="crtbegin.o crtbeginS.o crtend.o crtendS.o thumb.o"
+		extra_parts="crtbegin.o crtbeginS.o crtend.o crtendS.o"
 		gnu_ld=yes
 		case x${enable_threads} in
 		x | xyes | xpthreads | xposix)
@@ -3614,38 +3606,27 @@ for machine in $build $host $target; do
 	arm*-*-uclinux*)		# ARM ucLinux
 		tm_file=arm/uclinux-elf.h
 		tmake_file=arm/t-arm-elf
-		extra_objs=thumb.o
 		;;
 	arm*-*-aout)
 		tm_file=arm/aout.h
 		tmake_file=arm/t-arm-aout
-		extra_objs=thumb.o
 		;;
         arm*-*-ecos-elf)
 		tm_file=arm/ecos-elf.h
 		tmake_file=arm/t-arm-elf
-		extra_objs=thumb.o
 		;; 
 	arm*-*-elf)
 		tm_file=arm/unknown-elf.h
 		tmake_file=arm/t-arm-elf
-		extra_objs=thumb.o
 		;;
         arm*-*-oabi)
 		tm_file=arm/unknown-elf-oabi.h
 		tmake_file=arm/t-arm-elf
-		extra_objs=thumb.o
 		;;
 	arm-*-pe*)
 		tm_file=arm/pe.h
 		tmake_file=arm/t-pe
-		extra_objs="pe.o thumb.o"
-		;;
-	thumb*-*-*)
-		{ echo "configure: error: 
-*** The Thumb targets have been depreciated.  The equivalent
-*** ARM based toolchain can now generated Thumb instructions
-*** when the -mthumb switch is given to the compiler." 1>&2; exit 1; }
+		extra_objs="pe.o"
 		;;
 	c1-convex-*)			# Convex C1
 		target_cpu_default=1
@@ -5892,7 +5873,7 @@ for machine in $build $host $target; do
 	sparc-*-netbsd*)
 		tm_file=sparc/netbsd.h
 		tmake_file=t-netbsd
-       use_collect2=yes
+		use_collect2=yes
 		;;
 	sparc-*-openbsd*)
 		# we need collect2 until our bug is fixed...
@@ -6112,6 +6093,12 @@ for machine in $build $host $target; do
 #		;;
 #	tahoe-*-bsd*)			# tahoe running BSD
 #		;;
+	thumb*-*-*)
+		{ echo "configure: error: 
+*** The Thumb targets have been depreciated.  The equivalent
+*** ARM based toolchain can now generated Thumb instructions
+*** when the -mthumb switch is given to the compiler." 1>&2; exit 1; }
+		;;
 
 # This hasn't been upgraded to GCC 2.
 #	tron-*-*)
