Enable loop bundle again.

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -22957,6 +22957,42 @@ $as_echo "#define HAVE_GAS_NSUBSPA_COMDAT 1" >>confdefs.h
 fi
 
 
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking assembler for .bundle_align_mode extended" >&5
+$as_echo_n "checking assembler for .bundle_align_mode extended... " >&6; }
+if ${gcc_cv_as_bundle_align_mode_extended+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  gcc_cv_as_bundle_align_mode_extended=no
+    if test $in_tree_gas = yes; then
+    if test $gcc_cv_gas_vers -ge `expr \( \( 2 \* 1000 \) + 33 \) \* 1000 + 0`
+  then gcc_cv_as_bundle_align_mode_extended=yes
+fi
+  elif test x$gcc_cv_as != x; then
+    $as_echo '.bundle_align_mode 6,7,0' > conftest.s
+    if { ac_try='$gcc_cv_as $gcc_cv_as_flags  -o conftest.o conftest.s >&5'
+  { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_try\""; } >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; }
+    then
+	gcc_cv_as_bundle_align_mode_extended=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $gcc_cv_as_bundle_align_mode_extended" >&5
+$as_echo "$gcc_cv_as_bundle_align_mode_extended" >&6; }
+if test $gcc_cv_as_bundle_align_mode_extended = yes; then
+
+$as_echo "#define HAVE_GAS_BUNDLE_ALIGN_MODE_EXTENDED 1" >>confdefs.h
+
+fi
+
+
 # .hidden needs to be supported in both the assembler and the linker,
 # because GNU LD versions before 2.12.1 have buggy support for STV_HIDDEN.
 # This is irritatingly difficult to feature test for; we have to check the
