Mainline merge as of 2002-06-16.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/ast-optimizer-branch@54690 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/configure.in b/gcc/configure.in
--- a/gcc/configure.in
+++ b/gcc/configure.in
@@ -869,6 +869,18 @@ if test x$thread_file = x; then
 	fi
 fi
 
+# Look for a file containing extra machine modes.
+if test -n "$extra_modes" && test -f $srcdir/config/$extra_modes; then
+  extra_modes_file='$(srcdir)'/config/${extra_modes}
+  AC_SUBST(extra_modes_file)
+  AC_DEFINE_UNQUOTED(EXTRA_MODES_FILE, "$extra_modes",
+  [Define to the name of a file containing a list of extra machine modes
+   for this architecture.])
+  AC_DEFINE(EXTRA_CC_MODES, 1,
+  [Define if the target architecture needs extra machine modes to represent
+   the results of comparisons.])
+fi
+
 # auto-host.h is the file containing items generated by autoconf and is
 # the first file included by config.h.
 # If host=build, it is correct to have hconfig include auto-host.h
@@ -2169,8 +2181,7 @@ if test x"${enable_languages+set}" != xset; then
 		enable_languages=all
 	fi
 else
-	if test x"${enable_languages}" = x ||
-	   test x"${enable_languages}" = xyes;
+	if test x"${enable_languages}" = x;
 	then
 		AC_MSG_ERROR([--enable-languages needs at least one language argument])
 	fi
@@ -2210,6 +2221,7 @@ changequote([,])dnl
    esac
 done
 
+remaining_languages=${enable_languages}
 subdirs=
 for lang in ${srcdir}/*/config-lang.in ..
 do
@@ -2235,6 +2247,7 @@ changequote(,)dnl
 	  *) add_this_lang=no ;;
 	  esac
 	  if test x"${add_this_lang}" = xyes; then
+                remaining_languages=`echo $remaining_languages | sed -e s/${lang_alias}//g`
 		case $lang in
 		    ${srcdir}/ada/config-lang.in)
 			if test x$have_gnat = xyes ; then
@@ -2250,6 +2263,14 @@ changequote(,)dnl
 changequote([,])dnl
 	esac
 done
+
+remaining_languages_check=`echo $remaining_languages | sed -e 's/,//g' -e 's/^c$//'g`
+if test "xxx$remaining_languages_check" != "xxx" -a "xxx$remaining_languages_check" != "xxxall" ; then
+    remaining_languages_clean=`echo $remaining_languages | sed -e 's/^c,//' -e 's/,c,/,/' -e 's/,c$//'  -e 's/^c$//' -e 's/,,*/,/g' -e 's/^,//g' -e 's/,$//g' `
+    echo "Language alias(es) not found: $remaining_languages_clean" 
+    echo "Refer to the configure instructions in the doc directory"
+    exit 1
+fi
 
 # Make gthr-default.h if we have a thread file.
 gthread_flags=
@@ -2314,6 +2335,16 @@ AC_ARG_ENABLE(sjlj-exceptions,
 [sjlj=`if test $enableval = yes; then echo 1; else echo 0; fi`
 AC_DEFINE_UNQUOTED(CONFIG_SJLJ_EXCEPTIONS, $sjlj,
   [Define 0/1 to force the choice for exception handling model.])])
+
+# Use libunwind based exception handling.
+AC_ARG_ENABLE(libunwind-exceptions,
+[  --enable-libunwind-exceptions  force use libunwind for exceptions],
+use_libunwind_exceptions=$enableval,
+use_libunwind_exceptions=no)
+if test x"$use_libunwind_exceptions" = xyes; then
+   AC_DEFINE(USE_LIBUNWIND_EXCEPTIONS, 1,
+	[Define if gcc should use -lunwind.])
+fi
 
 # Make empty files to contain the specs and options for each language.
 # Then add #include lines to for a compiler that has specs and/or options.
@@ -2564,6 +2595,7 @@ AC_SUBST(symbolic_link)
 AC_SUBST(thread_file)
 AC_SUBST(tm_file_list)
 AC_SUBST(tm_file)
+AC_SUBST(tm_defines)
 AC_SUBST(tm_p_file_list)
 AC_SUBST(tm_p_file)
 AC_SUBST(xm_file)
