* mainline merge (cfg-merge-20021206 tag)
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/cfg-branch@54557 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/configure.in b/gcc/configure.in
--- a/gcc/configure.in
+++ b/gcc/configure.in
@@ -264,6 +264,18 @@ elif test x$withval != xno; then
   cpp_install_dir=$withval
 fi])
 
+# Enable __cxa_atexit for C++.
+AC_ARG_ENABLE(__cxa_atexit,
+[  --enable-__cxa_atexit   enable __cxa_atexit for C++],
+[], [])
+if test x$enable___cxa_atexit = xyes; then
+  AC_DEFINE(DEFAULT_USE_CXA_ATEXIT, 1,
+  [Define if you want to use __cxa_atexit, rather than atexit, to
+   register C++ destructors for local statics and global objects.
+   This is essential for fully standards-compliant handling of
+   destructors, but requires __cxa_atexit in libc.])
+fi
+  
 # Enable Multibyte Characters for C/C++
 AC_ARG_ENABLE(c-mbchar,
 [  --enable-c-mbchar       enable multibyte characters for C and C++],
@@ -719,6 +731,7 @@ objext='.o'
 AC_SUBST(manext)
 AC_SUBST(objext)
 
+config_gtfiles=
 build_xm_file=
 build_xm_defines=
 build_install_headers_dir=install-headers-tar
@@ -854,6 +867,19 @@ if test x$thread_file = x; then
 	else
 		thread_file='single'
 	fi
+fi
+
+# Look for a file containing extra machine modes.
+if test -f $srcdir/config/${cpu_type}/${cpu_type}-modes.def; then
+  extra_modes_file='$(srcdir)/config/'${cpu_type}/${cpu_type}-modes.def
+  AC_SUBST(extra_modes_file)
+  AC_DEFINE_UNQUOTED(EXTRA_MODES_FILE,
+			   "${cpu_type}/${cpu_type}-modes.def",
+  [Define to the name of a file containing a list of extra machine modes
+   for this architecture.])
+  AC_DEFINE(EXTRA_CC_MODES, 1,
+  [Define if the target architecture needs extra machine modes to represent
+   the results of comparisons.])
 fi
 
 # auto-host.h is the file containing items generated by autoconf and is
@@ -2156,8 +2182,7 @@ if test x"${enable_languages+set}" != xset; then
 		enable_languages=all
 	fi
 else
-	if test x"${enable_languages}" = x ||
-	   test x"${enable_languages}" = xyes;
+	if test x"${enable_languages}" = x;
 	then
 		AC_MSG_ERROR([--enable-languages needs at least one language argument])
 	fi
@@ -2197,6 +2222,7 @@ changequote([,])dnl
    esac
 done
 
+remaining_languages=${enable_languages}
 subdirs=
 for lang in ${srcdir}/*/config-lang.in ..
 do
@@ -2222,6 +2248,7 @@ changequote(,)dnl
 	  *) add_this_lang=no ;;
 	  esac
 	  if test x"${add_this_lang}" = xyes; then
+                remaining_languages=`echo $remaining_languages | sed -e s/${lang_alias}//g`
 		case $lang in
 		    ${srcdir}/ada/config-lang.in)
 			if test x$have_gnat = xyes ; then
@@ -2237,6 +2264,14 @@ changequote(,)dnl
 changequote([,])dnl
 	esac
 done
+
+remaining_languages_check=`echo $remaining_languages | sed -e 's/,//g' -e 's/^c$//'g`
+if test "xxx$remaining_languages_check" != "xxx" -a "xxx$remaining_languages_check" != "xxxall" ; then
+    remaining_languages_clean=`echo $remaining_languages | sed -e 's/^c,//' -e 's/,c,/,/' -e 's/,c$//'  -e 's/^c$//' -e 's/,,*/,/g' -e 's/^,//g' -e 's/,$//g' `
+    echo "Language alias(es) not found: $remaining_languages_clean" 
+    echo "Refer to the configure instructions in the doc directory"
+    exit 1
+fi
 
 # Make gthr-default.h if we have a thread file.
 gthread_flags=
@@ -2331,7 +2366,7 @@ all_outputs='Makefile intl/Makefile fixinc/Makefile gccbug mklibgcc mkheaders'
 # List of language makefile fragments.
 all_lang_makefiles=
 # Files for gengtype
-all_gtfiles=
+all_gtfiles="$config_gtfiles"
 
 # Add the language fragments.
 # Languages are added via two mechanisms.  Some information must be
