Enable -mtls-markers
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/ibm@159048 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc-4_4-branch/gcc/configure b/gcc-4_4-branch/gcc/configure
--- a/gcc-4_4-branch/gcc/configure
+++ b/gcc-4_4-branch/gcc/configure
@@ -24035,6 +24035,89 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+
+    echo "$as_me:$LINENO: checking assembler for tls marker support" >&5
+echo $ECHO_N "checking assembler for tls marker support... $ECHO_C" >&6
+if test "${gcc_cv_as_powerpc_tls_markers+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  gcc_cv_as_powerpc_tls_markers=no
+    if test $in_tree_gas = yes; then
+    if test $gcc_cv_gas_vers -ge `expr \( \( 2 \* 1000 \) + 20 \) \* 1000 + 0`
+  then gcc_cv_as_powerpc_tls_markers=yes
+fi
+  elif test x$gcc_cv_as != x; then
+    echo ' bl __tls_get_addr(x@tlsgd)' > conftest.s
+    if { ac_try='$gcc_cv_as  -o conftest.o conftest.s >&5'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }
+    then
+	gcc_cv_as_powerpc_tls_markers=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+echo "$as_me:$LINENO: result: $gcc_cv_as_powerpc_tls_markers" >&5
+echo "${ECHO_T}$gcc_cv_as_powerpc_tls_markers" >&6
+if test $gcc_cv_as_powerpc_tls_markers = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AS_TLS_MARKERS 1
+_ACEOF
+
+fi
+
+    case $target in
+      *-*-aix*)
+	echo "$as_me:$LINENO: checking assembler for .ref support" >&5
+echo $ECHO_N "checking assembler for .ref support... $ECHO_C" >&6
+if test "${gcc_cv_as_aix_ref+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  gcc_cv_as_aix_ref=no
+    if test $in_tree_gas = yes; then
+    if test $gcc_cv_gas_vers -ge `expr \( \( 2.21.0 \* 1000 \) + gcc_cv_as_aix_ref=yes \) \* 1000 + `
+  then :
+fi
+  elif test x$gcc_cv_as != x; then
+    echo '	.csect stuff[rw]
+	     stuff:
+		.long 1
+		.extern sym
+		.ref sym
+	  ' > conftest.s
+    if { ac_try='$gcc_cv_as  -o conftest.o conftest.s >&5'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }
+    then
+	gcc_cv_as_aix_ref=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+echo "$as_me:$LINENO: result: $gcc_cv_as_aix_ref" >&5
+echo "${ECHO_T}$gcc_cv_as_aix_ref" >&6
+if test $gcc_cv_as_aix_ref = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AS_REF 1
+_ACEOF
+
+fi
+	;;
+    esac
     ;;
 
   mips*-*-*)
