Merge in 476 work
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/ibm@158389 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc-4_4-branch/gcc/configure b/gcc-4_4-branch/gcc/configure
--- a/gcc-4_4-branch/gcc/configure
+++ b/gcc-4_4-branch/gcc/configure
@@ -23953,6 +23953,52 @@ _ACEOF
 
 fi
 
+    case $target in
+      *-*-aix*) conftest_s='	.machine "476"
+	.csect .text[PR]
+	dci 0';;
+      *) conftest_s='	.machine "476"
+	.text
+	dci 0';;
+    esac
+
+    echo "$as_me:$LINENO: checking assembler for data cache invalidate support" >&5
+echo $ECHO_N "checking assembler for data cache invalidate support... $ECHO_C" >&6
+if test "${gcc_cv_as_powerpc_dci+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  gcc_cv_as_powerpc_dci=no
+    if test $in_tree_gas = yes; then
+    if test $gcc_cv_gas_vers -ge `expr \( \( 9 \* 1000 \) + 99 \) \* 1000 + 0`
+  then gcc_cv_as_powerpc_dci=yes
+fi
+  elif test x$gcc_cv_as != x; then
+    echo "$conftest_s" > conftest.s
+    if { ac_try='$gcc_cv_as -a32 -o conftest.o conftest.s >&5'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }
+    then
+	gcc_cv_as_powerpc_dci=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+echo "$as_me:$LINENO: result: $gcc_cv_as_powerpc_dci" >&5
+echo "${ECHO_T}$gcc_cv_as_powerpc_dci" >&6
+if test $gcc_cv_as_powerpc_dci = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AS_DCI 1
+_ACEOF
+
+fi
+
     echo "$as_me:$LINENO: checking assembler for .gnu_attribute support" >&5
 echo $ECHO_N "checking assembler for .gnu_attribute support... $ECHO_C" >&6
 if test "${gcc_cv_as_powerpc_gnu_attribute+set}" = set; then
