Bugfix in automatic recognition of binutils kind for cil32
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/st@145585 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/cli-be/gcc/configure b/cli-be/gcc/configure
--- a/cli-be/gcc/configure
+++ b/cli-be/gcc/configure
@@ -16506,6 +16506,22 @@ _ACEOF
 
 fi
 
+case "$target" in
+   cil32-*-*)
+     if ${gcc_cv_ld} -h | grep "GCC4CLI" > /dev/null; then
+       tm_defines="${tm_defines} MONO_BINUTILS=1"
+     else
+       if ${gcc_cv_ld} -h | grep "Southern Storm Software" > /dev/null; then
+         tm_defines="${tm_defines} DOTGNU_BINUTILS=1"
+       else
+         { { echo "$as_me:$LINENO: error: Unrecognized binutils: impossible to choose default compiler driver arguments" >&5
+echo "$as_me: error: Unrecognized binutils: impossible to choose default compiler driver arguments" >&2;}
+   { (exit 1); exit 1; }; }
+       fi
+     fi
+   ;;
+esac
+
 # Test for stack protector support in target C library.
 echo "$as_me:$LINENO: checking __stack_chk_fail in target C library" >&5
 echo $ECHO_N "checking __stack_chk_fail in target C library... $ECHO_C" >&6
