libjava/
2008-09-14  Matthias Klose  <doko@ubuntu.com>

	Import GNU Classpath (libgcj-import-20080914).

	* Regenerate class and header files.
	* Regenerate auto* files.
	* configure.ac: Don't pass --disable-gjdoc to classpath.
	* sources.am: Regenerated.
	* HACKING: Mention to build gjdoc in maintainer builds.
	* gnu/classpath/Configuration.java: Update classpath version.
	* gcj/javaprims.h: Update.

libjava/classpath/

2008-09-14  Matthias Klose  <doko@ubuntu.com>

	* m4/ac_prog_javac_works.m4, m4/ac_prog_javac.m4, m4/acinclude.m4:
	Revert local changes.
	* m4/ac_prog_antlr.m4: Check for an runantlr binary.
	* tools/Makefile.am, lib/Makefile.am: Revert local changes (JCOMPILER).
	* tools/Makefile.am: Remove USE_JAVAC_FLAGS, pass ANTLR_JAR in
	GLIBJ_CLASSPATH.

2008-09-14  Matthias Klose  <doko@ubuntu.com>

	Revert:
	Daniel Frampton  <zyridium at zyridium.net>

	* AUTHORS: Added.
	* java/lang/InheritableThreadLocal.java,
	* java/lang/Thread.java,
	* java/lang/ThreadLocal.java:
	Modified to use java.lang.ThreadLocalMap.
	* java/lang/ThreadLocalMap.java:
	New cheaper ThreadLocal-specific WeakHashMap.


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/gcj@140367 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/classpath-098-merge-branch/libjava/classpath/configure b/classpath-098-merge-branch/libjava/classpath/configure
--- a/classpath-098-merge-branch/libjava/classpath/configure
+++ b/classpath-098-merge-branch/libjava/classpath/configure
@@ -461,7 +461,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os JAVA_MAINTAINER_MODE_TRUE JAVA_MAINTAINER_MODE_FALSE GENINSRC_TRUE GENINSRC_FALSE multi_basedir LIBVERSION CLASSPATH_MODULE CLASSPATH_CONVENIENCE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CREATE_COLLECTIONS_TRUE CREATE_COLLECTIONS_FALSE CREATE_JNI_LIBRARIES_TRUE CREATE_JNI_LIBRARIES_FALSE CREATE_CORE_JNI_LIBRARIES_TRUE CREATE_CORE_JNI_LIBRARIES_FALSE CREATE_GCONF_PEER_LIBRARIES_TRUE CREATE_GCONF_PEER_LIBRARIES_FALSE CREATE_GSTREAMER_PEER_LIBRARIES_TRUE CREATE_GSTREAMER_PEER_LIBRARIES_FALSE default_toolkit CREATE_XMLJ_LIBRARY_TRUE CREATE_XMLJ_LIBRARY_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CREATE_ALSA_LIBRARIES_TRUE CREATE_ALSA_LIBRARIES_FALSE CREATE_DSSI_LIBRARIES_TRUE CREATE_DSSI_LIBRARIES_FALSE CREATE_GTK_PEER_LIBRARIES_TRUE CREATE_GTK_PEER_LIBRARIES_FALSE CREATE_QT_PEER_LIBRARIES_TRUE CREATE_QT_PEER_LIBRARIES_FALSE CREATE_PLUGIN_TRUE CREATE_PLUGIN_FALSE CREATE_GJDOC_TRUE CREATE_GJDOC_FALSE toolexeclibdir nativeexeclibdir glibjdir CREATE_JNI_HEADERS_TRUE CREATE_JNI_HEADERS_FALSE CREATE_WRAPPERS_TRUE CREATE_WRAPPERS_FALSE LN_S LIBTOOL SED FGREP GREP LD DUMPBIN ac_ct_DUMPBIN NM AR ac_ct_AR RANLIB ac_ct_RANLIB lt_ECHO CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP PERL COLLECTIONS_PREFIX LIBMAGIC LIBICONV LTLIBICONV WARNING_CFLAGS EXTRA_CFLAGS STRICT_WARNING_CFLAGS ERROR_CFLAGS PKG_CONFIG XML_CFLAGS XML_LIBS XSLT_CFLAGS XSLT_LIBS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS GTK_CFLAGS GTK_LIBS FREETYPE2_CFLAGS FREETYPE2_LIBS PANGOFT2_CFLAGS PANGOFT2_LIBS CAIRO_CFLAGS CAIRO_LIBS XTEST_LIBS GCONF_CFLAGS GCONF_LIBS GDK_CFLAGS GDK_LIBS GSTREAMER_CFLAGS GSTREAMER_LIBS GSTREAMER_BASE_CFLAGS GSTREAMER_BASE_LIBS GSTREAMER_PLUGINS_BASE_CFLAGS GSTREAMER_PLUGINS_BASE_LIBS GST_PLUGIN_LDFLAGS GSTREAMER_FILE_READER GSTREAMER_MIXER_PROVIDER QT_CFLAGS QT_LIBS MOC MOZILLA_CFLAGS MOZILLA_LIBS GLIB_CFLAGS GLIB_LIBS PLUGIN_DIR GMP_CFLAGS GMP_LIBS USER_JAVAH CLASSPATH_INCLUDES vm_classes MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBDEBUG INIT_LOAD_LIBRARY ECJ_JAR JAVA_LANG_SYSTEM_EXPLICIT_INITIALIZATION REMOVE MKDIR CP DATE FIND ZIP JAR WITH_JAR_TRUE WITH_JAR_FALSE INSTALL_GLIBJ_ZIP_TRUE INSTALL_GLIBJ_ZIP_FALSE INSTALL_CLASS_FILES_TRUE INSTALL_CLASS_FILES_FALSE BUILD_CLASS_FILES_TRUE BUILD_CLASS_FILES_FALSE EXAMPLESDIR TOOLSDIR GJDOC CREATE_API_DOCS_TRUE CREATE_API_DOCS_FALSE JAY JAY_SKELETON REGEN_PARSERS_TRUE REGEN_PARSERS_FALSE USE_PREBUILT_GLIBJ_ZIP_TRUE USE_PREBUILT_GLIBJ_ZIP_FALSE PATH_TO_GLIBJ_ZIP JAVA uudecode JAVAC ANTLR ANTLR_JAR JAVAC_MEM_OPT USE_ESCHER_TRUE USE_ESCHER_FALSE PATH_TO_ESCHER ENABLE_LOCAL_SOCKETS_TRUE ENABLE_LOCAL_SOCKETS_FALSE DEFAULT_PREFS_PEER WANT_NATIVE_BIG_INTEGER CREATE_GMPBI_LIBRARY_TRUE CREATE_GMPBI_LIBRARY_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os JAVA_MAINTAINER_MODE_TRUE JAVA_MAINTAINER_MODE_FALSE GENINSRC_TRUE GENINSRC_FALSE multi_basedir LIBVERSION CLASSPATH_MODULE CLASSPATH_CONVENIENCE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CREATE_COLLECTIONS_TRUE CREATE_COLLECTIONS_FALSE CREATE_JNI_LIBRARIES_TRUE CREATE_JNI_LIBRARIES_FALSE CREATE_CORE_JNI_LIBRARIES_TRUE CREATE_CORE_JNI_LIBRARIES_FALSE CREATE_GCONF_PEER_LIBRARIES_TRUE CREATE_GCONF_PEER_LIBRARIES_FALSE CREATE_GSTREAMER_PEER_LIBRARIES_TRUE CREATE_GSTREAMER_PEER_LIBRARIES_FALSE default_toolkit CREATE_XMLJ_LIBRARY_TRUE CREATE_XMLJ_LIBRARY_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CREATE_ALSA_LIBRARIES_TRUE CREATE_ALSA_LIBRARIES_FALSE CREATE_DSSI_LIBRARIES_TRUE CREATE_DSSI_LIBRARIES_FALSE CREATE_GTK_PEER_LIBRARIES_TRUE CREATE_GTK_PEER_LIBRARIES_FALSE CREATE_QT_PEER_LIBRARIES_TRUE CREATE_QT_PEER_LIBRARIES_FALSE CREATE_PLUGIN_TRUE CREATE_PLUGIN_FALSE CREATE_GJDOC_TRUE CREATE_GJDOC_FALSE toolexeclibdir nativeexeclibdir glibjdir CREATE_JNI_HEADERS_TRUE CREATE_JNI_HEADERS_FALSE CREATE_WRAPPERS_TRUE CREATE_WRAPPERS_FALSE LN_S LIBTOOL SED FGREP GREP LD DUMPBIN ac_ct_DUMPBIN NM AR ac_ct_AR RANLIB ac_ct_RANLIB lt_ECHO CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP PERL COLLECTIONS_PREFIX LIBMAGIC LIBICONV LTLIBICONV WARNING_CFLAGS EXTRA_CFLAGS STRICT_WARNING_CFLAGS ERROR_CFLAGS PKG_CONFIG XML_CFLAGS XML_LIBS XSLT_CFLAGS XSLT_LIBS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS GTK_CFLAGS GTK_LIBS FREETYPE2_CFLAGS FREETYPE2_LIBS PANGOFT2_CFLAGS PANGOFT2_LIBS CAIRO_CFLAGS CAIRO_LIBS XTEST_LIBS GCONF_CFLAGS GCONF_LIBS GDK_CFLAGS GDK_LIBS GSTREAMER_CFLAGS GSTREAMER_LIBS GSTREAMER_BASE_CFLAGS GSTREAMER_BASE_LIBS GSTREAMER_PLUGINS_BASE_CFLAGS GSTREAMER_PLUGINS_BASE_LIBS GST_PLUGIN_LDFLAGS GSTREAMER_FILE_READER GSTREAMER_MIXER_PROVIDER QT_CFLAGS QT_LIBS MOC MOZILLA_CFLAGS MOZILLA_LIBS GLIB_CFLAGS GLIB_LIBS PLUGIN_DIR GMP_CFLAGS GMP_LIBS USER_JAVAH CLASSPATH_INCLUDES vm_classes MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBDEBUG INIT_LOAD_LIBRARY ECJ_JAR JAVA_LANG_SYSTEM_EXPLICIT_INITIALIZATION REMOVE MKDIR CP DATE FIND ZIP JAR WITH_JAR_TRUE WITH_JAR_FALSE INSTALL_GLIBJ_ZIP_TRUE INSTALL_GLIBJ_ZIP_FALSE INSTALL_CLASS_FILES_TRUE INSTALL_CLASS_FILES_FALSE BUILD_CLASS_FILES_TRUE BUILD_CLASS_FILES_FALSE EXAMPLESDIR TOOLSDIR GJDOC CREATE_API_DOCS_TRUE CREATE_API_DOCS_FALSE JAY JAY_SKELETON REGEN_PARSERS_TRUE REGEN_PARSERS_FALSE USE_PREBUILT_GLIBJ_ZIP_TRUE USE_PREBUILT_GLIBJ_ZIP_FALSE PATH_TO_GLIBJ_ZIP JAVA uudecode JAVAC JAVAC_IS_GCJ GCJ_JAVAC_TRUE GCJ_JAVAC_FALSE ANTLR ac_ct_ANTLR ANTLR_JAR JAVAC_MEM_OPT USE_ESCHER_TRUE USE_ESCHER_FALSE PATH_TO_ESCHER ENABLE_LOCAL_SOCKETS_TRUE ENABLE_LOCAL_SOCKETS_FALSE DEFAULT_PREFS_PEER WANT_NATIVE_BIG_INTEGER CREATE_GMPBI_LIBRARY_TRUE CREATE_GMPBI_LIBRARY_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 ac_pwd=`pwd`
 
@@ -25156,7 +25156,6 @@ else
 fi;
 
 
-
 if test "x${WITH_GJDOC}" = xyes; then
   CREATE_API_DOCS_TRUE=
   CREATE_API_DOCS_FALSE='#'
@@ -25165,6 +25164,20 @@ else
   CREATE_API_DOCS_FALSE=
 fi
 
+  if test "x${WITH_GJDOC}" = xyes; then
+    echo "$as_me:$LINENO: checking version of GJDoc" >&5
+echo $ECHO_N "checking version of GJDoc... $ECHO_C" >&6
+    gjdoc_version=$(${GJDOC} --version|cut -d ' ' -f2)
+    echo "$as_me:$LINENO: result: ${gjdoc_version}" >&5
+echo "${ECHO_T}${gjdoc_version}" >&6
+    case ${gjdoc_version} in
+      0.7.9) ;;
+      0.8*) ;;
+      *) { { echo "$as_me:$LINENO: error: Building documentation requires GJDoc >= 0.7.9, ${gjdoc_version} found." >&5
+echo "$as_me: error: Building documentation requires GJDoc >= 0.7.9, ${gjdoc_version} found." >&2;}
+   { (exit 1); exit 1; }; } ;;
+    esac
+  fi
 
 
 
@@ -28392,7 +28405,7 @@ EOF
 if uudecode$EXEEXT Test.uue; then
         ac_cv_prog_uudecode_base64=yes
 else
-        echo "configure: 28395: uudecode had trouble decoding base 64 file 'Test.uue'" >&5
+        echo "configure: 28408: uudecode had trouble decoding base 64 file 'Test.uue'" >&5
         echo "configure: failed file was:" >&5
         cat Test.uue >&5
         ac_cv_prog_uudecode_base64=no
@@ -28415,6 +28428,7 @@ echo "$as_me: error: Cannot compile java source. $JAVAC does not work properly" 
 
 ECJ_OPTS="-warn:-deprecation,serial,unusedImport"
 JAVAC_OPTS="-Xlint:unchecked,cast,divzero,empty,finally,overrides"
+GCJ_OPTS="-g"
 if test "x$JAVAPREFIX" = x; then
         test "x$JAVAC" = x && for ac_prog in "ecj$EXEEXT $ECJ_OPTS" "ecj-3.3$EXEEXT $ECJ_OPTS" "ecj-3.2$EXEEXT $ECJ_OPTS" "javac$EXEEXT $JAVAC_OPTS" "gcj$EXEEXT -C"
 do
@@ -28502,7 +28516,31 @@ fi
 test "x$JAVAC" = x && { { echo "$as_me:$LINENO: error: no acceptable Java compiler found in \$PATH" >&5
 echo "$as_me: error: no acceptable Java compiler found in \$PATH" >&2;}
    { (exit 1); exit 1; }; }
-if test "$enable_java_maintainer_mode" = yes; then
+echo "$as_me:$LINENO: checking if $JAVAC is a version of gcj" >&5
+echo $ECHO_N "checking if $JAVAC is a version of gcj... $ECHO_C" >&6
+if test "${ac_cv_prog_javac_is_gcj+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+if $JAVAC --version | grep gcj > /dev/null; then
+  ac_cv_prog_javac_is_gcj=yes;
+  JAVAC="$JAVAC $GCJ_OPTS";
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_prog_javac_is_gcj" >&5
+echo "${ECHO_T}$ac_cv_prog_javac_is_gcj" >&6
+JAVAC_IS_GCJ=$ac_cv_prog_javac_is_gcj
+
+
+
+if test x"${JAVAC_IS_GCJ}" = xyes; then
+  GCJ_JAVAC_TRUE=
+  GCJ_JAVAC_FALSE='#'
+else
+  GCJ_JAVAC_TRUE='#'
+  GCJ_JAVAC_FALSE=
+fi
+
 
 echo "$as_me:$LINENO: checking if $JAVAC works" >&5
 echo $ECHO_N "checking if $JAVAC works... $ECHO_C" >&6
@@ -28513,7 +28551,7 @@ else
 JAVA_TEST=Object.java
 CLASS_TEST=Object.class
 cat << \EOF > $JAVA_TEST
-/* #line 28516 "configure" */
+/* #line 28554 "configure" */
 package java.lang;
 
 public class Object
@@ -28523,7 +28561,12 @@ public class Object
   }
 }
 EOF
-if { ac_try='$JAVAC $JAVA_TEST'
+if test x$JAVAC_IS_GCJ = xyes; then
+  CMD="$JAVAC $JAVACFLAGS -fsource=1.5 -ftarget=1.5 $JAVA_TEST"
+else
+  CMD="$JAVAC $JAVACFLAGS -source 1.5 -target 1.5 $JAVA_TEST"
+fi
+if { ac_try='$CMD'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -28543,7 +28586,6 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_prog_javac_works" >&5
 echo "${ECHO_T}$ac_cv_prog_javac_works" >&6
 
-fi
 
         fi
 fi
@@ -28557,7 +28599,7 @@ JAVA_TEST=Test.java
 CLASS_TEST=Test.class
 TEST=Test
 cat << \EOF > $JAVA_TEST
-/* [#]line 28560 "configure" */
+/* [#]line 28602 "configure" */
 public class Test {
 public static void main (String args[]) {
         System.exit (0);
@@ -28602,7 +28644,9 @@ echo "${ECHO_T}$ac_cv_prog_java_works" >&6
 
 
   fi
-  if test "x${COMPILE_GJDOC}" = xyes; then
+fi
+
+if test "x${COMPILE_GJDOC}" = xyes; then
 
   if test -z "$ANTLR_JAR"; then
           echo "$as_me:$LINENO: checking for antlr 2.7.1 or better" >&5
@@ -28641,8 +28685,102 @@ echo "$as_me: error: specified ANTLR jar file $ANTLR_JAR not found." >&2;}
         && { echo "$as_me:$LINENO: using ANTLR parser generator in $ANTLR_JAR" >&5
 echo "$as_me: using ANTLR parser generator in $ANTLR_JAR" >&6;}
   fi
-  ANTLR="$JAVA -classpath $ANTLR_JAR antlr.Tool"
-  test -z $ANTLR_JAR && \
+  if test -n "$ac_tool_prefix"; then
+  for ac_prog in runantlr
+  do
+    # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
+set dummy $ac_tool_prefix$ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_ANTLR+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$ANTLR"; then
+  ac_cv_prog_ANTLR="$ANTLR" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_ANTLR="$ac_tool_prefix$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+ANTLR=$ac_cv_prog_ANTLR
+if test -n "$ANTLR"; then
+  echo "$as_me:$LINENO: result: $ANTLR" >&5
+echo "${ECHO_T}$ANTLR" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+    test -n "$ANTLR" && break
+  done
+fi
+if test -z "$ANTLR"; then
+  ac_ct_ANTLR=$ANTLR
+  for ac_prog in runantlr
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_ac_ct_ANTLR+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$ac_ct_ANTLR"; then
+  ac_cv_prog_ac_ct_ANTLR="$ac_ct_ANTLR" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_ac_ct_ANTLR="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+ac_ct_ANTLR=$ac_cv_prog_ac_ct_ANTLR
+if test -n "$ac_ct_ANTLR"; then
+  echo "$as_me:$LINENO: result: $ac_ct_ANTLR" >&5
+echo "${ECHO_T}$ac_ct_ANTLR" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$ac_ct_ANTLR" && break
+done
+
+  ANTLR=$ac_ct_ANTLR
+fi
+
+  if test "x$ANTLR" = x; then
+      if test -z "$JAVA"; then
+        { { echo "$as_me:$LINENO: error: no suitable runantlr found and no suitable java runtime found." >&5
+echo "$as_me: error: no suitable runantlr found and no suitable java runtime found." >&2;}
+   { (exit 1); exit 1; }; }
+      else
+        ANTLR="$JAVA -classpath $ANTLR_JAR antlr.Tool"
+      fi
+  fi
+  test -z "$ANTLR_JAR" && \
         { { echo "$as_me:$LINENO: error: no suitable antlr.jar found for version 2.7.1" >&5
 echo "$as_me: error: no suitable antlr.jar found for version 2.7.1" >&2;}
    { (exit 1); exit 1; }; }
@@ -28651,7 +28789,6 @@ echo "${ECHO_T}$antlr_use_major.$antlr_use_minor.$antlr_use_micro" >&6
 
 
 
-  fi
 fi
 
 # Check for javac if we need to build either the class library,
@@ -28663,6 +28800,7 @@ if test "x${use_glibj_zip}" = xfalse || \
 
 ECJ_OPTS="-warn:-deprecation,serial,unusedImport"
 JAVAC_OPTS="-Xlint:unchecked,cast,divzero,empty,finally,overrides"
+GCJ_OPTS="-g"
 if test "x$JAVAPREFIX" = x; then
         test "x$JAVAC" = x && for ac_prog in "ecj$EXEEXT $ECJ_OPTS" "ecj-3.3$EXEEXT $ECJ_OPTS" "ecj-3.2$EXEEXT $ECJ_OPTS" "javac$EXEEXT $JAVAC_OPTS" "gcj$EXEEXT -C"
 do
@@ -28750,7 +28888,31 @@ fi
 test "x$JAVAC" = x && { { echo "$as_me:$LINENO: error: no acceptable Java compiler found in \$PATH" >&5
 echo "$as_me: error: no acceptable Java compiler found in \$PATH" >&2;}
    { (exit 1); exit 1; }; }
-if test "$enable_java_maintainer_mode" = yes; then
+echo "$as_me:$LINENO: checking if $JAVAC is a version of gcj" >&5
+echo $ECHO_N "checking if $JAVAC is a version of gcj... $ECHO_C" >&6
+if test "${ac_cv_prog_javac_is_gcj+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+if $JAVAC --version | grep gcj > /dev/null; then
+  ac_cv_prog_javac_is_gcj=yes;
+  JAVAC="$JAVAC $GCJ_OPTS";
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_prog_javac_is_gcj" >&5
+echo "${ECHO_T}$ac_cv_prog_javac_is_gcj" >&6
+JAVAC_IS_GCJ=$ac_cv_prog_javac_is_gcj
+
+
+
+if test x"${JAVAC_IS_GCJ}" = xyes; then
+  GCJ_JAVAC_TRUE=
+  GCJ_JAVAC_FALSE='#'
+else
+  GCJ_JAVAC_TRUE='#'
+  GCJ_JAVAC_FALSE=
+fi
+
 
 echo "$as_me:$LINENO: checking if $JAVAC works" >&5
 echo $ECHO_N "checking if $JAVAC works... $ECHO_C" >&6
@@ -28761,7 +28923,7 @@ else
 JAVA_TEST=Object.java
 CLASS_TEST=Object.class
 cat << \EOF > $JAVA_TEST
-/* #line 28764 "configure" */
+/* #line 28926 "configure" */
 package java.lang;
 
 public class Object
@@ -28771,7 +28933,12 @@ public class Object
   }
 }
 EOF
-if { ac_try='$JAVAC $JAVA_TEST'
+if test x$JAVAC_IS_GCJ = xyes; then
+  CMD="$JAVAC $JAVACFLAGS -fsource=1.5 -ftarget=1.5 $JAVA_TEST"
+else
+  CMD="$JAVAC $JAVACFLAGS -source 1.5 -target 1.5 $JAVA_TEST"
+fi
+if { ac_try='$CMD'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -28791,13 +28958,12 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_prog_javac_works" >&5
 echo "${ECHO_T}$ac_cv_prog_javac_works" >&6
 
-fi
 
 
   JAVA_TEST=Test.java
   CLASS_TEST=Test.class
   cat << \EOF > $JAVA_TEST
-  /* #line 28800 "configure" */
+  /* #line 28966 "configure" */
   public class Test
   {
     public static void main(String args)
@@ -28806,17 +28972,19 @@ fi
     }
   }
 EOF
-  echo "$as_me:$LINENO: checking whether javac supports -J" >&5
+  if test x$JAVAC_IS_GCJ != xyes; then
+    echo "$as_me:$LINENO: checking whether javac supports -J" >&5
 echo $ECHO_N "checking whether javac supports -J... $ECHO_C" >&6
-  $JAVAC $JAVACFLAGS -J-Xmx768M $JAVA_TEST
-  javac_result=$?
-  if test "x$javac_result" = "x0"; then
-    echo "$as_me:$LINENO: result: yes" >&5
+    $JAVAC $JAVACFLAGS -J-Xmx768M -sourcepath '' $JAVA_TEST
+    javac_result=$?
+    if test "x$javac_result" = "x0"; then
+      echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    JAVAC_MEM_OPT="-J-Xmx768M"
-  else
-    echo "$as_me:$LINENO: result: no" >&5
+      JAVAC_MEM_OPT="-J-Xmx768M"
+    else
+      echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
+    fi
   fi
   rm -f $JAVA_TEST $CLASS_TEST
 
@@ -29516,6 +29684,20 @@ if test -z "${USE_PREBUILT_GLIBJ_ZIP_TRUE}" && test -z "${USE_PREBUILT_GLIBJ_ZIP
   { { echo "$as_me:$LINENO: error: conditional \"USE_PREBUILT_GLIBJ_ZIP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"USE_PREBUILT_GLIBJ_ZIP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${GCJ_JAVAC_TRUE}" && test -z "${GCJ_JAVAC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"GCJ_JAVAC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"GCJ_JAVAC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${GCJ_JAVAC_TRUE}" && test -z "${GCJ_JAVAC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"GCJ_JAVAC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"GCJ_JAVAC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -30719,7 +30901,11 @@ s,@PATH_TO_GLIBJ_ZIP@,$PATH_TO_GLIBJ_ZIP,;t t
 s,@JAVA@,$JAVA,;t t
 s,@uudecode@,$uudecode,;t t
 s,@JAVAC@,$JAVAC,;t t
+s,@JAVAC_IS_GCJ@,$JAVAC_IS_GCJ,;t t
+s,@GCJ_JAVAC_TRUE@,$GCJ_JAVAC_TRUE,;t t
+s,@GCJ_JAVAC_FALSE@,$GCJ_JAVAC_FALSE,;t t
 s,@ANTLR@,$ANTLR,;t t
+s,@ac_ct_ANTLR@,$ac_ct_ANTLR,;t t
 s,@ANTLR_JAR@,$ANTLR_JAR,;t t
 s,@JAVAC_MEM_OPT@,$JAVAC_MEM_OPT,;t t
 s,@USE_ESCHER_TRUE@,$USE_ESCHER_TRUE,;t t
