2008-09-29  Matthias Klose  <doko@ubuntu.com>
	* m4/ac_prog_antlr.m4: Check for antlr binary as well.


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/gcj@140761 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/classpath-098-merge-branch/libjava/classpath/configure b/classpath-098-merge-branch/libjava/classpath/configure
--- a/classpath-098-merge-branch/libjava/classpath/configure
+++ b/classpath-098-merge-branch/libjava/classpath/configure
@@ -29756,7 +29756,7 @@ echo "$as_me: error: specified ANTLR jar file $ANTLR_JAR not found." >&2;}
 echo "$as_me: using ANTLR parser generator in $ANTLR_JAR" >&6;}
   fi
   if test -n "$ac_tool_prefix"; then
-  for ac_prog in runantlr
+  for ac_prog in runantlr antlr
   do
     # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
 set dummy $ac_tool_prefix$ac_prog; ac_word=$2
@@ -29798,7 +29798,7 @@ fi
 fi
 if test -z "$ANTLR"; then
   ac_ct_ANTLR=$ANTLR
-  for ac_prog in runantlr
+  for ac_prog in runantlr antlr
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -29843,8 +29843,8 @@ fi
 
   if test "x$ANTLR" = x; then
       if test -z "$JAVA"; then
-        { { echo "$as_me:$LINENO: error: no suitable runantlr found and no suitable java runtime found." >&5
-echo "$as_me: error: no suitable runantlr found and no suitable java runtime found." >&2;}
+        { { echo "$as_me:$LINENO: error: no suitable antlr binary found and no suitable java runtime found." >&5
+echo "$as_me: error: no suitable antlr binary found and no suitable java runtime found." >&2;}
    { (exit 1); exit 1; }; }
       else
         ANTLR="$JAVA -classpath $ANTLR_JAR antlr.Tool"
