Merge between /tags/var-tracking-assignments-merge-132391-trunk-4_3-branchpoint and /tags/var-tracking-assignments-4_3-merge-138264-4_3/.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/var-tracking-assignments-4_3-branch@138284 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/libstdc++-v3/include/Makefile.in b/libstdc++-v3/include/Makefile.in
--- a/libstdc++-v3/include/Makefile.in
+++ b/libstdc++-v3/include/Makefile.in
@@ -308,7 +308,6 @@ std_headers = \
 	${std_srcdir}/stdexcept \
 	${std_srcdir}/streambuf \
 	${std_srcdir}/string \
-	${std_srcdir}/system_error \
 	${std_srcdir}/tuple \
 	${std_srcdir}/type_traits \
 	${std_srcdir}/unordered_map \
@@ -402,7 +401,7 @@ backward_headers = \
 	${backward_srcdir}/hash_set \
 	${backward_srcdir}/hash_fun.h \
 	${backward_srcdir}/hashtable.h \
-	${backward_srcdir}/strstream 
+	${backward_srcdir}/strstream
 
 pb_srcdir = ${glibcxx_srcdir}/include/ext/pb_ds
 pb_builddir = ./ext/pb_ds
@@ -434,7 +433,7 @@ pb_subdirs = \
 
 
 # The ability for make and the underlying host to deal with this
-# unweildy list as one entire entity is not a sure thing, and may
+# unwieldy list as one entire entity is not a sure thing, and may
 # cause build errors. Thus, split one list into many smaller
 # mini-lists, with the maximum size per mini-list of no more than 42.
 pb_headers1 = \
@@ -478,7 +477,7 @@ pb_headers1 = \
 	${pb_srcdir}/detail/binomial_heap_/debug_fn_imps.hpp \
 	${pb_srcdir}/detail/bin_search_tree_/bin_search_tree_.hpp \
 	${pb_srcdir}/detail/bin_search_tree_/cond_dtor_entry_dealtor.hpp \
-	${pb_srcdir}/detail/bin_search_tree_/cond_key_dtor_entry_dealtor.hpp 
+	${pb_srcdir}/detail/bin_search_tree_/cond_key_dtor_entry_dealtor.hpp
 
 pb_headers2 = \
 	${pb_srcdir}/detail/bin_search_tree_/constructors_destructor_fn_imps.hpp \
@@ -520,7 +519,7 @@ pb_headers2 = \
 	${pb_srcdir}/detail/cc_hash_table_map_/resize_no_store_hash_fn_imps.hpp \
 	${pb_srcdir}/detail/cc_hash_table_map_/resize_store_hash_fn_imps.hpp \
 	${pb_srcdir}/detail/cc_hash_table_map_/size_fn_imps.hpp \
-	${pb_srcdir}/detail/cc_hash_table_map_/standard_policies.hpp 
+	${pb_srcdir}/detail/cc_hash_table_map_/standard_policies.hpp
 
 pb_headers3 = \
 	${pb_srcdir}/detail/cc_hash_table_map_/trace_fn_imps.hpp \
@@ -561,7 +560,7 @@ pb_headers3 = \
 	${pb_srcdir}/detail/hash_fn/probe_fn_base.hpp \
 	${pb_srcdir}/detail/hash_fn/quadratic_probe_fn_imp.hpp \
 	${pb_srcdir}/detail/hash_fn/ranged_hash_fn.hpp \
-	${pb_srcdir}/detail/hash_fn/ranged_probe_fn.hpp 
+	${pb_srcdir}/detail/hash_fn/ranged_probe_fn.hpp
 
 pb_headers4 = \
 	${pb_srcdir}/detail/hash_fn/sample_probe_fn.hpp \
@@ -604,7 +603,7 @@ pb_headers4 = \
 	${pb_srcdir}/detail/ov_tree_map_/insert_fn_imps.hpp \
 	${pb_srcdir}/detail/ov_tree_map_/iterators_fn_imps.hpp \
 	${pb_srcdir}/detail/ov_tree_map_/node_iterators.hpp \
-	${pb_srcdir}/detail/ov_tree_map_/ov_tree_map_.hpp 
+	${pb_srcdir}/detail/ov_tree_map_/ov_tree_map_.hpp
 
 pb_headers5 = \
 	${pb_srcdir}/detail/ov_tree_map_/policy_access_fn_imps.hpp \
@@ -646,7 +645,7 @@ pb_headers5 = \
 	${pb_srcdir}/detail/pat_trie_/update_fn_imps.hpp \
 	${pb_srcdir}/detail/priority_queue_base_dispatch.hpp \
 	${pb_srcdir}/detail/rb_tree_map_/constructors_destructor_fn_imps.hpp \
-	${pb_srcdir}/detail/rb_tree_map_/debug_fn_imps.hpp 
+	${pb_srcdir}/detail/rb_tree_map_/debug_fn_imps.hpp
 
 pb_headers6 = \
 	${pb_srcdir}/detail/rb_tree_map_/erase_fn_imps.hpp \
@@ -688,7 +687,7 @@ pb_headers6 = \
 	${pb_srcdir}/detail/standard_policies.hpp \
 	${pb_srcdir}/detail/thin_heap_/constructors_destructor_fn_imps.hpp \
 	${pb_srcdir}/detail/thin_heap_/debug_fn_imps.hpp \
-	${pb_srcdir}/detail/thin_heap_/erase_fn_imps.hpp 
+	${pb_srcdir}/detail/thin_heap_/erase_fn_imps.hpp
 
 pb_headers7 = \
 	${pb_srcdir}/detail/thin_heap_/find_fn_imps.hpp \
@@ -714,10 +713,10 @@ pb_headers7 = \
 	${pb_srcdir}/detail/unordered_iterator/const_iterator.hpp \
 	${pb_srcdir}/detail/unordered_iterator/const_point_iterator.hpp \
 	${pb_srcdir}/detail/unordered_iterator/iterator.hpp \
-	${pb_srcdir}/detail/unordered_iterator/point_iterator.hpp 
+	${pb_srcdir}/detail/unordered_iterator/point_iterator.hpp
 
 ext_srcdir = ${glibcxx_srcdir}/include/ext
-ext_builddir = ./ext 
+ext_builddir = ./ext
 ext_headers = \
 	${ext_srcdir}/algorithm \
 	${ext_srcdir}/atomicity.h \
@@ -884,7 +883,7 @@ c_compatibility_builddir = .
 @GLIBCXX_C_HEADERS_C_GLOBAL_TRUE@c_compatibility_headers = \
 @GLIBCXX_C_HEADERS_C_GLOBAL_TRUE@	${c_compatibility_srcdir}/complex.h \
 @GLIBCXX_C_HEADERS_C_GLOBAL_TRUE@	${c_compatibility_srcdir}/fenv.h \
-@GLIBCXX_C_HEADERS_C_GLOBAL_TRUE@	${c_compatibility_srcdir}/tgmath.h 
+@GLIBCXX_C_HEADERS_C_GLOBAL_TRUE@	${c_compatibility_srcdir}/tgmath.h
 
 @GLIBCXX_C_HEADERS_C_STD_TRUE@c_compatibility_headers = 
 @GLIBCXX_C_HEADERS_C_TRUE@c_compatibility_headers = \
@@ -946,9 +945,8 @@ debug_headers = \
 parallel_srcdir = ${glibcxx_srcdir}/include/parallel
 parallel_builddir = ./parallel
 parallel_headers = \
-        ${parallel_srcdir}/algorithm \
-        ${parallel_srcdir}/algobase.h \
         ${parallel_srcdir}/algo.h \
+        ${parallel_srcdir}/algobase.h \
         ${parallel_srcdir}/algorithm \
         ${parallel_srcdir}/algorithmfwd.h \
         ${parallel_srcdir}/balanced_quicksort.h \
@@ -974,8 +972,8 @@ parallel_headers = \
         ${parallel_srcdir}/numericfwd.h \
         ${parallel_srcdir}/omp_loop.h \
         ${parallel_srcdir}/omp_loop_static.h \
-        ${parallel_srcdir}/parallel.h \
         ${parallel_srcdir}/par_loop.h \
+        ${parallel_srcdir}/parallel.h \
         ${parallel_srcdir}/partial_sum.h \
         ${parallel_srcdir}/partition.h \
         ${parallel_srcdir}/queue.h \
@@ -989,7 +987,7 @@ parallel_headers = \
         ${parallel_srcdir}/tags.h \
         ${parallel_srcdir}/types.h \
         ${parallel_srcdir}/unique_copy.h \
-        ${parallel_srcdir}/workstealing.h 
+        ${parallel_srcdir}/workstealing.h
 
 @GLIBCXX_C_HEADERS_EXTRA_FALSE@c_base_headers_extra = 
 
@@ -1010,10 +1008,9 @@ host_headers = \
 	${glibcxx_srcdir}/$(ATOMIC_WORD_SRCDIR)/atomic_word.h \
 	${glibcxx_srcdir}/$(ABI_TWEAKS_SRCDIR)/cxxabi_tweaks.h \
 	${glibcxx_srcdir}/$(CPU_DEFINES_SRCDIR)/cpu_defines.h \
-	${glibcxx_srcdir}/$(ERROR_CONSTANTS_SRCDIR)/error_constants.h \
 	${glibcxx_srcdir}/include/precompiled/stdc++.h \
 	${glibcxx_srcdir}/include/precompiled/stdtr1c++.h \
-	${glibcxx_srcdir}/include/precompiled/extc++.h 
+	${glibcxx_srcdir}/include/precompiled/extc++.h
 
 
 # Non-installed host_header files.
@@ -1031,7 +1028,7 @@ host_headers_extra = \
 	${host_builddir}/c++io.h \
 	${host_builddir}/c++locale.h \
 	${host_builddir}/messages_members.h \
-	${host_builddir}/time_members.h 
+	${host_builddir}/time_members.h
 
 thread_host_headers = \
 	${host_builddir}/gthr.h \
@@ -1255,72 +1252,46 @@ uninstall-am: uninstall-info-am
 # Here are the rules for building the headers
 all-local: ${allstamped} ${allcreated}
 
-# This rule is slightly different, in that we must change the name of the
-# local file from std_foo.h to foo.
+# Ignore errors from 'mkdir -p' to avoid parallel make failure on
+# systems with broken mkdir.  Call mkdir unconditionally because
+# it is just as cheap to avoid going through the shell.
+# Ignore errors from $(LN_S) because the links may already exist.
 stamp-std: ${std_headers}
-	@if [ ! -d "${std_builddir}" ]; then \
-	  mkdir -p ${std_builddir} ;\
-	fi ;\
-	if [ ! -f stamp-std ]; then \
-	  (cd ${std_builddir} && $(LN_S) $? . || true) ;\
-	fi ;\
-	$(STAMP) stamp-std
+	@-mkdir -p ${std_builddir}
+	@-cd ${std_builddir} && $(LN_S) $? . 2>/dev/null
+	@$(STAMP) stamp-std
 
 stamp-bits: ${bits_headers}
-	@if [ ! -d "${bits_builddir}" ]; then \
-	  mkdir -p ${bits_builddir} ;\
-	fi ;\
-	if [ ! -f stamp-bits ]; then \
-	  (cd ${bits_builddir} && $(LN_S) $? . || true) ;\
-	fi ;\
-	$(STAMP) stamp-bits
+	@-mkdir -p ${bits_builddir}
+	@-cd ${bits_builddir} && $(LN_S) $? . 2>/dev/null
+	@$(STAMP) stamp-bits
 
-stamp-c_base: ${c_base_headers} 
-	@if [ ! -d "${c_base_builddir}" ]; then \
-	  mkdir -p ${c_base_builddir} ;\
-	fi ;\
-	if [ ! -f stamp-c_base ]; then \
-	  (cd ${c_base_builddir} && $(LN_S) $? . || true) ;\
-	fi ;\
-	$(STAMP) stamp-c_base
+stamp-c_base: ${c_base_headers}
+	@-mkdir -p ${c_base_builddir}
+	@-cd ${c_base_builddir} && $(LN_S) $? . 2>/dev/null
+	@$(STAMP) stamp-c_base
 
 stamp-c_base_extra: ${c_base_headers_extra}
-	@if [ ! -d "${bits_builddir}" ]; then \
-	  mkdir -p ${bits_builddir} ;\
-	fi ;\
-	if [ ! -f stamp-c_base_extra ]; then \
-	  (cd ${bits_builddir} && $(LN_S) $? . || true) ;\
-	fi ;\
-	$(STAMP) stamp-c_base_extra
+	@-mkdir -p ${bits_builddir}
+	@-cd ${bits_builddir} && $(LN_S) $? . 2>/dev/null
+	@$(STAMP) stamp-c_base_extra
 
 stamp-c_compatibility: ${c_compatibility_headers_extra}
-	@if [ ! -d "${c_compatibility_builddir}" ]; then \
-	  mkdir -p ${c_compatibility_builddir} ;\
-	fi ;\
-	if [ ! -f stamp-c_compatibility ]; then \
-	  if [ ! -z "${c_compatibility_headers_extra}" ]; then \
-	    (cd ${c_compatibility_builddir} && $(LN_S) $? . || true) ;\
-	  fi ;\
-	fi ;\
-	$(STAMP) stamp-c_compatibility
+	@-mkdir -p ${c_compatibility_builddir}
+	@-if [ ! -z "${c_compatibility_headers_extra}" ]; then \
+	  cd ${c_compatibility_builddir} && $(LN_S) $? . 2>/dev/null ;\
+	fi
+	@$(STAMP) stamp-c_compatibility
 
 stamp-backward: ${backward_headers}
-	@if [ ! -d "${backward_builddir}" ]; then \
-	  mkdir -p ${backward_builddir} ;\
-	fi ;\
-	if [ ! -f stamp-backward ]; then \
-	  (cd ${backward_builddir} && $(LN_S) $? . || true) ;\
-	fi ;\
-	$(STAMP) stamp-backward
+	@-mkdir -p ${backward_builddir}
+	@-cd ${backward_builddir} && $(LN_S) $? . 2>/dev/null
+	@$(STAMP) stamp-backward
 
 stamp-ext: ${ext_headers}
-	@if [ ! -d "${ext_builddir}" ]; then \
-	    mkdir -p ${ext_builddir} ;\
-	fi ;\
-	if [ ! -f stamp-ext ]; then \
-	  (cd ${ext_builddir} && $(LN_S) $? . || true) ;\
-	fi ;\
-	$(STAMP) stamp-ext
+	@-mkdir -p ${ext_builddir}
+	@-cd ${ext_builddir} && $(LN_S) $? . 2>/dev/null
+	@$(STAMP) stamp-ext
 
 # Have to deal with nested include directories, gah! Strip off source
 # directory before making the link.
@@ -1328,7 +1299,7 @@ stamp-ext: ${ext_headers}
 stamp-pb:
 	@if [ ! -d "${pb_builddir}" ]; then \
 	    mkdir -p ${pb_subdirs} ;\
-	fi 
+	fi
 	@if [ ! -f stamp-pb ]; then \
 	    cd ${pb_builddir} && for h in ${pb_headers1}; do \
 		build_name=`echo $$h | sed -e "s|${pb_srcdir}|.|g"` ;\
@@ -1374,52 +1345,33 @@ stamp-pb:
 	$(STAMP) stamp-pb
 
 stamp-tr1: ${tr1_headers}
-	@if [ ! -d "${tr1_builddir}" ]; then \
-	    mkdir -p ${tr1_builddir} ;\
-	fi ;\
-	if [ ! -f stamp-tr1 ]; then \
-	  (cd ${tr1_builddir} && $(LN_S) $? . || true) ;\
-	fi ;\
-	$(STAMP) stamp-tr1
+	@-mkdir -p ${tr1_builddir}
+	@-cd ${tr1_builddir} && $(LN_S) $? . 2>/dev/null
+	@$(STAMP) stamp-tr1
 
 stamp-tr1-impl: ${tr1_impl_headers}
-	@if [ ! -d "${tr1_impl_builddir}" ]; then \
-	    mkdir -p ${tr1_impl_builddir} ;\
-	fi ;\
-	if [ ! -f stamp-tr1-impl ]; then \
-	  (cd ${tr1_impl_builddir} && $(LN_S) $? . || true) ;\
-	fi ;\
-	$(STAMP) stamp-tr1-impl
+	@-mkdir -p ${tr1_impl_builddir}
+	@-cd ${tr1_impl_builddir} && $(LN_S) $? . 2>/dev/null
+	@$(STAMP) stamp-tr1-impl
 
 stamp-debug: ${debug_headers}
-	@if [ ! -d "${debug_builddir}" ]; then \
-	  mkdir -p ${debug_builddir} ;\
-	fi ;\
-	if [ ! -f stamp-debug ]; then \
-	  (cd ${debug_builddir} && @LN_S@ $? . || true) ;\
-	fi ;\
-	$(STAMP) stamp-debug
+	@-mkdir -p ${debug_builddir}
+	@-cd ${debug_builddir} && $(LN_S) $? . 2>/dev/null
+	@$(STAMP) stamp-debug
 
 stamp-parallel: ${parallel_headers}
-	@if [ ! -d "${parallel_builddir}" ]; then \
-	  mkdir -p ${parallel_builddir} ;\
-	fi ;\
-	if [ ! -f stamp-parallel ]; then \
-	  (cd ${parallel_builddir} && @LN_S@ $? . || true) ;\
-	fi ;\
-	$(STAMP) stamp-parallel
+	@-mkdir -p ${parallel_builddir}
+	@-cd ${parallel_builddir} && $(LN_S) $? . 2>/dev/null
+	@$(STAMP) stamp-parallel
 
 stamp-${host_alias}:
-	@if [ ! -d ${host_builddir} ]; then \
-	  mkdir -p ${host_builddir} ;\
-	fi ;\
-	$(STAMP) stamp-${host_alias}
+	@-mkdir -p ${host_builddir}
+	@$(STAMP) stamp-${host_alias}
 
 # Host includes static.
 # XXX Missing dependency info for {host_headers_extra}
 stamp-host: ${host_headers} ${host_headers_noinst} stamp-${host_alias}
-	@if [ ! -f stamp-host ]; then \
-	  (cd ${host_builddir} ;\
+	@cd ${host_builddir} && {\
 	  $(LN_S) ${host_headers} . || true ;\
 	  $(LN_S) ${glibcxx_srcdir}/$(BASIC_FILE_H) basic_file.h || true ;\
 	  $(LN_S) ${glibcxx_srcdir}/$(ALLOCATOR_H) c++allocator.h || true ;\
@@ -1428,8 +1380,8 @@ stamp-host: ${host_headers} ${host_headers_noinst} stamp-${host_alias}
 	  $(LN_S) ${glibcxx_srcdir}/$(CLOCALE_INTERNAL_H) . || true ;\
 	  $(LN_S) ${glibcxx_srcdir}/$(COMPATIBILITY_H) . || true ;\
 	  $(LN_S) ${glibcxx_srcdir}/$(CMESSAGES_H) messages_members.h || true ;\
-	  $(LN_S) ${glibcxx_srcdir}/$(CTIME_H) time_members.h || true);\
-	fi ;\
+	  $(LN_S) ${glibcxx_srcdir}/$(CTIME_H) time_members.h || true;\
+	} 2>/dev/null
 	$(STAMP) stamp-host
 
 # Host includes dynamic.
@@ -1513,34 +1465,22 @@ ${host_builddir}/gthr-default.h: ${toplevel_srcdir}/gcc/${glibcxx_thread_h} \
 
 # Build two precompiled C++ includes, stdc++.h.gch/*.gch
 ${pch1a_output}: ${allstamped} ${host_builddir}/c++config.h ${pch1_source}
-	if [ ! -d "${pch1_output_builddir}" ]; then \
-	  mkdir -p ${pch1_output_builddir}; \
-	fi; \
+	-mkdir -p ${pch1_output_builddir}
 	$(CXX) $(PCHFLAGS) $(AM_CPPFLAGS) -O0 -g ${pch1_source} -o $@
-	touch ${pch1_output_anchor}
 
 ${pch1b_output}: ${allstamped} ${host_builddir}/c++config.h ${pch1_source}
-	if [ ! -d "${pch1_output_builddir}" ]; then \
-	  mkdir -p ${pch1_output_builddir}; \
-	fi; \
+	-mkdir -p ${pch1_output_builddir}
 	$(CXX) $(PCHFLAGS) $(AM_CPPFLAGS) -O2 -g ${pch1_source} -o $@
-	touch ${pch1_output_anchor}
 
 # Build a precompiled TR1 include, stdtr1c++.h.gch/O2.gch
 ${pch2_output}: ${pch2_source} ${pch1_output}
-	if [ ! -d "${pch2_output_builddir}" ]; then \
-	  mkdir -p ${pch2_output_builddir}; \
-	fi; \
+	-mkdir -p ${pch2_output_builddir}
 	$(CXX) $(PCHFLAGS) $(AM_CPPFLAGS) -O2 -g ${pch2_source} -o $@
-	touch ${pch2_output_anchor}
 
 # Build a precompiled extension include, extc++.h.gch/O2.gch
 ${pch3_output}: ${pch3_source} ${pch2_output}
-	if [ ! -d "${pch3_output_builddir}" ]; then \
-	  mkdir -p ${pch3_output_builddir}; \
-	fi; \
+	-mkdir -p ${pch3_output_builddir}
 	$(CXX) $(PCHFLAGS) $(AM_CPPFLAGS) -O2 -g ${pch3_source} -o $@
-	touch ${pch3_output_anchor}
 
 # For robustness sake (in light of junk files or in-source
 # configuration), copy from the build or source tree to the install
@@ -1551,7 +1491,7 @@ ${pch3_output}: ${pch3_source} ${pch2_output}
 # host_headers_extra are taken out of the build tree staging area;
 # the rest are taken from the original source tree.
 
-@GLIBCXX_HOSTED_TRUE@install-data-local: install-headers 
+@GLIBCXX_HOSTED_TRUE@install-data-local: install-headers
 @GLIBCXX_HOSTED_FALSE@install-data-local: install-freestanding-headers
 
 # This is a subset of the full install-headers rule.  We only need <cstddef>,
